### ISSUE TITLE
[REQUEST] Logging of player-written books + Dragon Egg movements

### ISSUE THREAD

**Issue by KFrohman** [LogBlock/LogBlock#193]
One of my players has built a very vast library for use of the players on my server, including provisions to write books, however, a written book in a chest, should it be affected by a rollback, no longer maintains any of its' contents - it turns into a blank item of 387. Whilst not a bug of LB itself, it's something I'd like to see implemented (if at all possible).

Also requested is logging of Dragon Egg movements. Someone has a dragon egg on display, and every so often someone will click it causing it to move to who knows where, all without a trace in logblock. Would like it so whenever the egg is moved, it shows who caused it to move, and to where it went.
Thanks.

**Comment by Brokkonaut** [comment]
Dragon Egg logging added in https://github.com/LogBlock/LogBlock/commit/95b7be57fcb410f315a1de33d967d77075772be3
Item meta logging somewhere earlier in 1.13
