### ISSUE TITLE
Creeper explosions logged as creeper even though logCreeperExplosionsAsPlayerWhoTriggeredThese: true

### ISSUE THREAD

**Issue by Dreytac** [LogBlock/LogBlock#219]
Using latest CraftBukkit-1.3.2-SNAPSHOT and LogBlock v1.58.

When checking for block destruction in an area, creeper explosions are logged as Creeper and not as the player who triggered the explosion.

**Comment by Brokkonaut** [comment]
I could not reproduce this issue
