### ISSUE TITLE
Can not rollback chests things.

### ISSUE THREAD

**Issue by snowsilk** [LogBlock/LogBlock#254]
Can not rollback chest thing.

All our user lose what they have in their Chests
I do not know if it's me or is it not possible with logblock.

If it's a tell me what needs to be turned on.

**Comment by Raymart23** [comment]
Hello how to rolback chest ?

**Comment by frymaster** [comment]
Make sure chest is logged: https://github.com/LogBlock/LogBlock/wiki/Configuration#logging    
Select "chestaccess" type in rollback params: https://github.com/LogBlock/LogBlock/wiki/Params#type
