### ISSUE TITLE
Please add ItemFrames Logging.

### ISSUE THREAD

**Issue by KaneHart** [LogBlock/LogBlock#266]
https://github.com/Bukkit/Bukkit/commit/ccd030487b22201cf45adafbc082bcbcf3c099f5

Thanks :)

**Comment by PiLoT-** [comment]
is there any update on this?

**Comment by lululombard** [comment]
I'm developping a plugin for LogBlock where new 1.8 blocks are logged and where Jukeboxes, Item Frames and painting are too. I'll say here when I'll release it.

**Comment by lululombard** [comment]
Put this in plugins folder : http://www.mediafire.com/download/jql33y8z2ywczlz/KingNewLog.jar
No configuration needed for now.
- Adds logs for Item Frames when you create them/destroy them/put something in it/remove from it (you can't rollback them, as LB API needs a Material that is a real block, I log it as "ender portal frame" so it can be messy if you rollback them)
- Adds logs for Cauldrons
- Adds logs when you open an anvil (as there is no use event)
- Adds logs when you right click a daylight sensor (inverting output state)
- Adds logs for new 1.8 wooden doors
- Adds logs for new 1.8 fences
- Adds logs when you put something in a flower pot
- Adds logs when you put/eject a record from a jukebox

And that's it, i'll do a bukkit page later ;)

**Comment by frymaster** [comment]
Do you plan on submitting these changes as a PR to logblock?

Or if you prefer, you could link the source code and I'd look into doing it for you

**Comment by lululombard** [comment]
Here's my Eclipse project folder : http://www.mediafire.com/download/262e0b4q125q4ww/KingNewLog.zip
Well, if you can do it I would be very pleased, but there should be somewhere where it checks if the logged material is a block, maybe add exception for item frames and paintins would be great.

**Comment by mibby** [comment]
Any update to this? Would love to be able to log _and_ rollback item frames. To a lesser extent, armor stands too. :(

**Comment by lululombard** [comment]
mibby : see this post : https://github.com/LogBlock/LogBlock/issues/266#issuecomment-116482026
You can log but not rollback with it.

**Comment by SXRWahrheit** [comment]
Rollback is needed for item frames. I would like to see this added.

**Comment by lululombard** [comment]
Sorry but I'm not going to do that unfortunatly :/

**Comment by mibby** [comment]
Guess LogBlock will never get proper itemframe (entity) logging / rollback. :(

@lululombard Would it be possible to implement config settings to disable logging not needed? I'd generally only like to be able to log item frames and armor stands. Also, what happens if you did a full player rollback and he has item frame logs? I don't mind that there is no rollback support, but would a full rollback cause problems if there is logs for an item frame?

**Comment by lululombard** [comment]
Well, I'm not doing plugins anymore, I mean I have to rest a bit. But rollbacks should not cause any problem.

**Comment by Brokkonaut** [comment]
Handled in #623
