### ISSUE TITLE
Log flows as the player

### ISSUE THREAD

**Issue by SuperPyroManiac** [LogBlock/LogBlock#277]
I was wondering if you could add an option to log water / lava flow as a player, such as how Coreprotect does it. I find it much easier to find the cause of the damage, and rollbacks work better. Since you can just rollback the player and not only is the water gone, but all the blocks the water destroyed were replaced since it would log like they destroyed torch.
Just an idea that I think would be useful.

Also while i'm here, ill let you know that it does NOT log firecharges!

**Comment by Brokkonaut** [comment]
Fixed some time ago
