### ISSUE TITLE
Chest access logging bug/issue

### ISSUE THREAD

**Issue by pips** [LogBlock/LogBlock#366]
It seems that there is a way to fake or avoid logging when accessing a chest. I've tested it with few different scenarios and each time I was able to recreate the issue.

If a player is alone, he can clear the chest without leaving any logs:
1. Player opens chest.
2. Takes stuff.
3. Before closing, he kills client (alt+f4 or other methods).
4. He logs back in. Items are in his inventory. No logs written for that chest.

In case he does that while other player has the same chest open, the logs of the other guy will be stored, when he closes the chest.

**Comment by Brokkonaut** [comment]
Was a bukkit bug, is fixed
