### ISSUE TITLE
[Feature request] Log GameMode of player for actions

### ISSUE THREAD

**Issue by possi** [LogBlock/LogBlock#387]
I would like to integrate the new feature of my plugin [LimitedCreative](http://dev.bukkit.org/server-mods/limited-creative/) with LogBlock. The "Block-GameMode"-Feature should prevent of drops of all blocks placed by creative players. In current implementation it needs its own database. When LogBlock would implement this field in every action, LimitedCreative could get the current state of it instead.

See also http://dev.bukkit.org/server-mods/limited-creative/?comment=497

**Comment by kgamecarter** [comment]
Can I log gamemode of create block by LogBlock 1.94?
