### ISSUE TITLE
Griefers can spam empty Signs without getting logged

### ISSUE THREAD

**Issue by jomo** [LogBlock/LogBlock#407]
Since signs are only logged when they have been placed **AND** text has been entered, griefers could simply place signs without beeing logged.

It would be simple to modify a client to abuse this.
# Repdroducing this issue
- Place a sign
- Do **not** hit the 'Done' button in the text editor
- Use console (or ask other player) to teleport you far away.  
  _(Or log off instead of teleporting)_.

**Comment by frymaster** [comment]
Tagged with "rollback" because if some signs are split into placement and editing then we'll want to check rollback, and especially redos, work properly
