### ISSUE TITLE
Logblock doesn't rollback placed blocks.

### ISSUE THREAD

**Issue by ghost** [LogBlock/LogBlock#438]
I tried rolling back some grief on the server today, and logblock only rolled back the destroyed blocks. It did nothing to the placed blocks whatsoever. This is a serious problem!

server version is 1.5.2

LB version is v1.70

**Comment by frymaster** [comment]
It looks like someone else had interfered with the blocks concerned. LB will only roll back if the block to be removed matches what was placed
