### ISSUE TITLE
Kills by arrow are attributed to "Arrow" rather than the shooter.

### ISSUE THREAD

**Issue by Hawkers** [LogBlock/LogBlock#470]
Is it possible to determine the originator of an arrow so the kill counts don't get thrown off?  Currently players who kill by bow and arrow don't get credit for those kills.

**Comment by MegaNarwhal** [comment]
I just recently enabled kill logging for all mobs on my survival server to be able to catch animal grief and noticed this. Makes kill logging useless against people who are killing animals from a distance or know they can evade being logged.
