### ISSUE TITLE
lookup date and rollback/redo date use different format

### ISSUE THREAD

**Issue by lightmaster** [LogBlock/LogBlock#502]
The date format that lookup uses by default is MM-dd(-yyyy if not current year), whereas the since and before params for rollback and redo use dd.MM.yyyy. If you accidently use MM.dd.yyyy for rollback or redo, then it will go back to the beginning of time and usually wipe out everything you've selected. This can even bypass time restrictions based on rank and that player can't undo it due to the rank restrictions.

I'd suggestion set both lookup command and since/before params to use the same date format to avoid putting in the round date, and also a check to make sure the since/before date is a valid date, not something like the 26th month, 08th day.

**Comment by frymaster** [comment]
no response
