### ISSUE TITLE
With the change to the map saving format to allow block ids > 256 by default, we should consider changing the database default field width to match

### ISSUE THREAD

**Issue by frymaster** [LogBlock/LogBlock#513]
Altering existing tables would be a PITA, but perhaps new ones should use SMALLINT instead of TINYINT

For "optional" schema changes to existing tables like that, or coord field increases, or playerid field increases, perhaps we should consider a command that will perform these.  As they aren't breaking changes, they could be performed async, and so not block the server starting up.  Changes to block logging tables are likely to be **very** time-intensive

**Comment by ammaraskar** [comment]
> As they aren't breaking changes, they could be performed async

You'd get a massive build up in the consumer as tables lock during schema changes

**Comment by Brokkonaut** [comment]
This should be fixed in the 1.13 update
