### ISSUE TITLE
API documentation unavailable

### ISSUE THREAD

**Issue by gdude2002** [LogBlock/LogBlock#514]
I'd looked over the cursory documentation [here](https://github.com/LogBlock/LogBlock/wiki/API#wiki-How_to_log_own_block_changes), and noted that it pointed to the following link for the javadoc: http://diddiz.insane-architects.net/LogBlock/doc/de/diddiz/LogBlock/Consumer.html#method_summary

However, as you can see, this doesn't exist anymore. Is there anywhere else this can be found?

**Comment by ammaraskar** [comment]
https://logblock.github.io/LogBlock/

**Comment by gdude2002** [comment]
<3
