### ISSUE TITLE
Add specific on or off functionality to /lb hide

### ISSUE THREAD

**Issue by nickperkins** [LogBlock/LogBlock#526]
/lb hide works as a toggle. This is fine when used in game but when used, for example, in a CommandHelper script it is not possible to know if you are turning hide on or off.

Would it be possible to have a way to explicitly turn hide on or off?

**Comment by LefsFlare** [comment]
Hey there! I'm not too sure if I'm qualified for this but I've took a little time and coded up a version that should do what you are asking for. You can try build 11 that I have on my build server

[DL Link](https://lefs.me/build/job/LogBlock%20-%20Developmental_UNSTABLE/11/de.diddiz$logblock/)
