### ISSUE TITLE
Exception, check error log. When using tool / toolblock

### ISSUE THREAD

**Issue by stalerin** [LogBlock/LogBlock#536]
My server hosting company website and servers went down yesterday and now LogBlock tools aren't working. It's not the hosting company because the MySQL and everything else works. I don't know where the log file is located, the only one i can find is just letters and symbols. There are no errors in the console or anywhere else I can see. The only thing that relates to LobBlock in the console is this.

27.02 18:48:07 [Server] INFO at de.diddiz.LogBlock.Consumer.run(Consumer.java:307) [LogBlock.jar:?]
27.02 18:48:07 [Server] INFO at de.diddiz.LogBlock.Consumer$BlockRow.executeStatements(Consumer.java:490) ~[LogBlock.jar:?]

That keeps popping up every 2 seconds, but I don't see any red flags in it, besides that it keeps popping up. The config files are all correct, It worked a little while ago, then just stopped after I restarted the server because no one was on. That's all the information I can think I should give, since I haven't installed any new plugins or changed the configs. If there's any advice I can get that would help a lot.

**Comment by dtrawick123** [comment]
I'm having the same error. Everytime I click a block I get this:

04.08 18:14:43 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_45]
04.08 18:14:43 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.7.0_45]
04.08 18:14:43 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.7.0_45]
04.08 18:14:43 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot.jar:git-Spigot-4faf77a-17a3db7]
04.08 18:14:43 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-4faf77a-17a3db7]
04.08 18:14:43 [Server] INFO at de.diddiz.LogBlock.CommandsHandler$CommandLookup.run(CommandsHandler.java:474) [LogBlock.jar:?]
04.08 18:14:43 [Server] INFO at de.diddiz.LogBlock.CommandsHandler.access$200(CommandsHandler.java:42) ~[LogBlock.jar:?]
04.08 18:14:43 [Server] INFO at de.diddiz.LogBlock.CommandsHandler.executeQuery(CommandsHandler.java:853) ~[LogBlock.jar:?]
04.08 18:14:43 [Server] INFO at com.zaxxer.hikari.proxy.StatementJavassistProxy.executeQuery(StatementJavassistProxy.java) ~[LogBlock.jar:?]
04.08 18:14:43 [Server] INFO at com.zaxxer.hikari.proxy.StatementProxy.executeQuery(StatementProxy.java:99) ~[LogBlock.jar:?]
04.08 18:14:43 [Server] INFO at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1474) ~[spigot.jar:git-Spigot-4faf77a-17a3db7]
04.08 18:14:43 [Server] INFO at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2570) ~[spigot.jar:git-Spigot-4faf77a-17a3db7]
04.08 18:14:43 [Server] INFO at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620) ~[spigot.jar:git-Spigot-4faf77a-17a3db7]
04.08 18:14:43 [Server] INFO at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140) ~[spigot.jar:git-Spigot-4faf77a-17a3db7]
04.08 18:14:43 [Server] INFO at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986) ~[spigot.jar:git-Spigot-4faf77a-17a3db7]
04.08 18:14:43 [Server] INFO at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525) ~[spigot.jar:git-Spigot-4faf77a-17a3db7]
04.08 18:14:43 [Server] INFO at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593) ~[spigot.jar:git-Spigot-4faf77a-17a3db7]
04.08 18:14:43 [Server] INFO at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052) ~[spigot.jar:git-Spigot-4faf77a-17a3db7]
04.08 18:14:43 [Server] INFO at com.mysql.jdbc.Util.getInstance(Util.java:382) ~[spigot.jar:git-Spigot-4faf77a-17a3db7]
04.08 18:14:43 [Server] INFO at com.mysql.jdbc.Util.handleNewInstance(Util.java:407) ~[spigot.jar:git-Spigot-4faf77a-17a3db7]
04.08 18:14:43 [Server] INFO at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.7.0_45]
04.08 18:14:43 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.7.0_45]
04.08 18:14:43 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.7.0_45]
04.08 18:14:43 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_45]
04.08 18:14:43 [Server] INFO com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'UUID' in 'field list'
04.08 18:14:43 [Server] ERROR SELECT date, replaced, type, data, playername, UUID, signtext, itemtype, itemamount, itemdata FROM `lb-world` INNER JOIN `lb-players` USING (playerid) LEFT JOIN `lb-world-sign` USING (id) LEFT JOIN `lb-world-chest` USING (id) WHERE x = 805 AND y = 17 AND z = 47 ORDER BY date DESC, id DESC LIMIT 15:


any help would be greatly appreciated. I'm using version 1.94 of logblock and spigot 1.8,  not certain of the exact build.

**Comment by frymaster** [comment]
This sounds like you connected an old database to a new logblock version without using the preexisting config file, so it didn't realise it needed to update the database.

Basically the database hasn't been updated to use UUIDs.  You can force this to happen by changing the version number in the config file to 1.89 while the server is stopped. See https://github.com/LogBlock/LogBlock/wiki/Converting-a-pre-existing-database-to-use-UUIDs for notes on the limitations of the migration system

**Comment by frymaster** [comment]
This is unrelated to OP's error, so to stop me from being confused I'm going to close this since OP never replied. Feel free to open a new issue if the previous comment didn't help
