### ISSUE TITLE
Use UUID to identify users

### ISSUE THREAD

**Issue by jomo** [LogBlock/LogBlock#538]
As of 1.7.6 using names will be deprecated and all things at Mojang will use UUIDs only.
As of 1.8.0 players will be able to change their names. ([source](https://github.com/Mojang/AccountsClient/issues/2#issuecomment-36437574))

You should store the UUID of a player to identify them after a possible name change.
calling [`getUniqueId()`](http://jd.bukkit.org/rb/doxygen/de/dd5/interfaceorg_1_1bukkit_1_1entity_1_1Entity.html#a4c23d9eeb686e0ea0a5969a3cc289a3e) on the player's entity will return the UUID (with dashes).

**Comment by frymaster** [comment]
I've booked some time off at the weekend, with the intention of finally moving forward on this. In order of importance:
- [ ] Historical records importer
- [ ] A couple of miscellaneous TODOs concerning the change to UUIDs
- [ ] Querying based on UUIDs
- [ ] Displaying UUIDs in output
- [ ] Integrating with #542

**Comment by DerFlash** [comment]
n1 thx!

Looking forward to it!

**Comment by jomo** [comment]
:+1: :shipit: :beer:

**Comment by jomo** [comment]
important:
> In addition, the **WorldEdit hook has been disabled** (is not compiled) since LB needs to be updated to use their new API, and the LB code hook has to extract UUID information for insertion.

**Comment by frymaster** [comment]
Yeah, the next step is #542 being updated to provide UUIDs
