### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by FootyInc** [LogBlock/LogBlock#551]
Im trying to find a build compable with Tekkit Classic and Feed The Beast unleashed.

Ive got database in and on load up it aint setting up the tables. (im using muiticraft panel)

Ive got it loggin correct world but when i do /lb me it states not loggin this world.

Not sure if plugin or SQL error.

![logblock error](https://cloud.githubusercontent.com/assets/7397255/2792143/964a90a0-cbce-11e3-8c94-d5fcb995c8d9.png)

**Comment by LefsFlare** [comment]
Well, there's your problem, this plugin isn't meant for Forge.
