### ISSUE TITLE
API documentation link dead

### ISSUE THREAD

**Issue by NixillUmbreon** [LogBlock/LogBlock#556]
On the API help page, https://github.com/LogBlock/LogBlock/wiki/API:

"To get a list of all queue methods have a look at the javadoc: http://diddiz.insane-architects.net/LogBlock/doc/de/diddiz/LogBlock/Consumer.html#method_summary"

The link leads to a domain-squatting page.

**Comment by ammaraskar** [comment]
poke

**Comment by ammaraskar** [comment]
https://logblock.github.io/LogBlock/
