### ISSUE TITLE
WorldEdit not Logged

### ISSUE THREAD

**Issue by ViscousSummer88** [LogBlock/LogBlock#557]
Hello, we have recently noticed that LogBlock does not log WorldEdit anyone.
LogBlock Version: 1.81
WorldEdit Version: v6.0.0-Snapshot:3165-75b9f3e
Server Version: Spigot, 1502

@md-5

**Comment by frymaster** [comment]
Fixed in 32ef8756f3335c617e2ee9dd8622b9bea1705730
