### ISSUE TITLE
I'm getting this error, can anyone help? It happens every time I use a lb command... 

### ISSUE THREAD

**Issue by Doco56** [LogBlock/LogBlock#559]
10.07 19:16:10 [Server] INFO at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [craftbukkit_179_beta.jar:git-Bukkit-1.7.9-R0.1-b3084jnks]
10.07 19:16:10 [Server] INFO at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:469) [craftbukkit_179_beta.jar:git-Bukkit-1.7.9-R0.1-b3084jnks]
10.07 19:16:10 [Server] INFO at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:558) [craftbukkit_179_beta.jar:git-Bukkit-1.7.9-R0.1-b3084jnks]
10.07 19:16:10 [Server] INFO at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:260) [craftbukkit_179_beta.jar:git-Bukkit-1.7.9-R0.1-b3084jnks]
10.07 19:16:10 [Server] INFO at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:667) [craftbukkit_179_beta.jar:git-Bukkit-1.7.9-R0.1-b3084jnks]
10.07 19:16:10 [Server] INFO at net.minecraft.server.v1_7_R3.ServerConnection.c(SourceFile:134) [craftbukkit_179_beta.jar:git-Bukkit-1.7.9-R0.1-b3084jnks]
10.07 19:16:10 [Server] INFO at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:157) [craftbukkit_179_beta.jar:git-Bukkit-1.7.9-R0.1-b3084jnks]
10.07 19:16:10 [Server] INFO at net.minecraft.server.v1_7_R3.PacketPlayInChat.handle(PacketPlayInChat.java:47) [craftbukkit_179_beta.jar:git-Bukkit-1.7.9-R0.1-b3084jnks]
10.07 19:16:10 [Server] INFO at net.minecraft.server.v1_7_R3.PacketPlayInChat.a(PacketPlayInChat.java:28) [craftbukkit_179_beta.jar:git-Bukkit-1.7.9-R0.1-b3084jnks]
10.07 19:16:10 [Server] INFO at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java:817) [craftbukkit_179_beta.jar:git-Bukkit-1.7.9-R0.1-b3084jnks]
10.07 19:16:10 [Server] INFO at net.minecraft.server.v1_7_R3.PlayerConnection.handleCommand(PlayerConnection.java:956) [craftbukkit_179_beta.jar:git-Bukkit-1.7.9-R0.1-b3084jnks]
10.07 19:16:10 [Server] INFO at org.bukkit.craftbukkit.v1_7_R3.CraftServer.dispatchCommand(CraftServer.java:701) [craftbukkit_179_beta.jar:git-Bukkit-1.7.9-R0.1-b3084jnks]
10.07 19:16:10 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:180) [craftbukkit_179_beta.jar:git-Bukkit-1.7.9-R0.1-b3084jnks]
10.07 19:16:10 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [craftbukkit_179_beta.jar:git-Bukkit-1.7.9-R0.1-b3084jnks]
10.07 19:16:10 [Server] INFO at de.diddiz.LogBlock.CommandsHandler.onCommand(CommandsHandler.java:134) [LogBlock.jar:?]
10.07 19:16:10 [Server] INFO java.lang.NullPointerException
10.07 19:16:10 [Server] WARN Exception in commands handler:

**Comment by frymaster** [comment]
No response
