### ISSUE TITLE
 [ERROR]: Could not pass event BlockBreakEvent

### ISSUE THREAD

**Issue by CLGREEN94** [LogBlock/LogBlock#560]
Good afternoon guys. 

So I am having a little issue with Logblock when my plugin hooks into logblock it every so often will throw this error and it can become quite spammy. 

Just looking for some feedback on how to fix it or what's wrong with it. 

I am running the following:

Logblock: 1.81

Bukkit: Bukkit-1.7.2-R0.2-41-g3c20ce6-b3012jnks

java: java version "1.7.0_55"
OpenJDK Runtime Environment (rhel-2.4.7.1.el6_5-x86_64 u55-b13)
OpenJDK 64-Bit Server VM (build 24.51-b03, mixed mode)

Error : http://pastebin.com/GEtWMDS3

Thanks guys :)

**Comment by frymaster** [comment]
Sorry for the lack of response - did you ever figure this out?

**Comment by CLGREEN94** [comment]
It's all good man. I know you are all busy with other stuff. I have no idea what the fate of LB is :( It upsets me. Honestly I thought you closed this months ago :')
