### ISSUE TITLE
[LogBlock] Error while loading: Table 'logblock.lb-players' doesn't exist

### ISSUE THREAD

**Issue by Lyndariel** [LogBlock/LogBlock#569]
Hi there,

After a crash I've got an error in Logblock:

[LogBlock] Error while loading: Table 'logblock.lb-players' doesn't exist

Any ideas how to fix it?

greetings
Lyndariel

**Comment by frymaster** [comment]
Hi, was your issue solved?

If not, can you paste your startup log?

**Comment by Lyndariel** [comment]
We fixed it, but thanks for reply
