### ISSUE TITLE
1.8 New Blocks Not Logged Correctly

### ISSUE THREAD

**Issue by johnjuhl** [LogBlock/LogBlock#571]
The new door types don't log for who opens and closes them, just for who places/destroys them. Armor Stands work similarly, where it shows that a player has placed a stand (Not properly, "player did an unspecified action") but it doesn't log them being broken. I think they are an entity though so that makes sense.

![logblock](https://cloud.githubusercontent.com/assets/4647054/5486630/82a9d110-865d-11e4-942c-aeacba8f546a.PNG)

**Comment by Mahagon** [comment]
i think logblock needs to build against bukkit 1.8
there is no official repo by bukkit but spigot has a fork

https://bukkit.org/threads/bukkit-1-8-maven-repo-now-available.326850/

maybe we could use that one? :)

**Comment by frymaster** [comment]
We **will** need to do that, but I'm trying to get all the other low-to-medium hanging fruit out the way before we stop being 1.7 compatible

**Comment by minifisch** [comment]
Any updates on this?

**Comment by Brokkonaut** [comment]
Fixed in the 1.13 update
