### ISSUE TITLE
Logblock and NameChnages. 

### ISSUE THREAD

**Issue by CLGREEN94** [LogBlock/LogBlock#573]
I just thought I would bringing it to the attention to the LogBlock Dev I.e @md-5 that log block is checking for when people change there name for example my in-game name is CLGREEN if i change my name to CLRED when i use log block it will only show CLGREEN and not CLRED made any changes. 

I don't know if you all have stopped support for log block but I do think this is something that needs to be looked at and maybe see if there is anything that can be done? 

Thanks

- Callum (CLGREEN).

**Comment by frymaster** [comment]
Fixed in latest builds
