### ISSUE TITLE
LogBlock throwing IOException when trying to convert names to UUIDs

### ISSUE THREAD

**Issue by SullyTheUnusual** [LogBlock/LogBlock#576]
[20:31:39 ERROR]: [UUID importer]
java.io.IOException: Server returned HTTP response code: 429 for URL: https://api.mojang.com/profiles/minecraft
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1839) ~[?:1.8.0_31]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440) ~[?:1.8.0_31]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[?:1.8.0_31]
        at de.diddiz.util.UUIDFetcher.getUUIDs(UUIDFetcher.java:29) ~[LogBlock.jar:?]
        at de.diddiz.LogBlock.Updater.update(Updater.java:314) [LogBlock.jar:?]
        at de.diddiz.LogBlock.LogBlock.onLoad(LogBlock.java:90) [LogBlock.jar:?]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:293) [spigot.jar:git-Spigot-d5bf866-917e46a]
        at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:152) [spigot.jar:git-Spigot-d5bf866-917e46a]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494) [spigot.jar:git-Spigot-d5bf866-917e46a]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]

**Comment by frymaster** [comment]
429 is ["too many requests"](http://httpstatusdogs.com/429-too-many-requests) - I'm guessing you have a **lot** of players?  I could never get this to trigger in testing (apart from the time I accidentally ended up in an infinite loop....) so I didn't make any attempt to throttle things

Before that was logged, were you seeing "Processed *x* out of *y*"?  If so, wait a short while and restart the server, and it should continue to migrate people.  If not, you've found a bug, and I need to look further. Please let me know how you get on

**Comment by SullyTheUnusual** [comment]
I have over 14,000 logged player names.  I tried it a couple times and never got any messages about anything being processed.  These is the console output immediately prior to the exception:

[20:31:39 INFO]: [LogBlock] Loading LogBlock v1.91
[20:31:39 INFO]: [LogBlock] Connecting to minecraft@jdbc:mysql://localhost:3306/global_logblock?useUnicode=true&characterEncoding=utf-8...
[20:31:39 INFO]: Updating tables to 1.81 ...
[20:31:39 INFO]: Updating tables to 1.9 ...
[20:31:39 INFO]: Importing UUIDs for large databases may take some time
[20:31:39 INFO]: 14340 players to convert
--throws exception--

**Comment by frymaster** [comment]
Here's a debug build I'd like you to try here:

http://ci.frymaster.127001.org/job/logblock-debug/lastBuild/de.diddiz$logblock/artifact/de.diddiz/logblock/dev-SNAPSHOT/logblock-dev-SNAPSHOT.jar

Warning, I expect this is going to spam your logs **a lot**.  Can you stick the complete server log on https://gist.github.com/ or similar, or zip it up and host it somewhere?

**Comment by SullyTheUnusual** [comment]
Can send you the log in an email or PM somewhere?  I want to protect user privacy.

**Comment by frymaster** [comment]
sure, my email address is my username here, at the domain 127001.org

**Comment by SullyTheUnusual** [comment]
Ok, sent the log.

**Comment by frymaster** [comment]
wow. OK, it really **is** just failing on the very first request.  Are you on shared hosting? Is it possible someone else on that IP is spamming Mojang's profile service?

**Comment by SullyTheUnusual** [comment]
I'm currently tethered to my phone for internet, and I'm the only one using
it.  I can test again when I get home if you'd like.

**Comment by frymaster** [comment]
It's possible your phone provider is routing the request though some kind of non-transparent proxy which would mean you'd be "sharing" an IP with many thousands of other people.  Please test again when you get home and we'll see if that's the issue

**Comment by SullyTheUnusual** [comment]
Sorry, I deleted that comment when I realized I wasn't running the server on my machine.  It's a friend's machine that is set up for testing and upgrading our MC server, and I don't believe the IP is shared with anyone.

**Comment by frymaster** [comment]
Right, in that case

1) Can you try to download the URL https://api.mojang.com/users/profiles/minecraft/frymaster from that machine and tell me if it succeeds (you should get back a small json file) or errors out with 429?

2) Assuming it succeeds, can you try [this](http://ci.frymaster.127001.org/job/logblock-debug/3/de.diddiz$logblock/artifact/de.diddiz/logblock/dev-SNAPSHOT/logblock-dev-SNAPSHOT.jar) ? It's a build with the number of names sent in one request dropped down to 50 instead of 100

(I'd almost expect that to spam the service *more*, since that means less of a delay between requests, but given yours is failing on the very first request...)

**Comment by SullyTheUnusual** [comment]
Ok, No.1 succeeded, and No.2 ran through all 14,000+ names, but looks like they all returned "not found" and got the "noimport" tag.  Sent you the log via email.

**Comment by frymaster** [comment]
They didn't ALL return "not found" or that log would have been a helluva lot larger!

What's happened is that those players changed their name, and so the migration tool can't work out what their UUID should be.  See [this](https://github.com/LogBlock/LogBlock/wiki/FAQ#warning-logblock-updater-playername-not-found---giving-uuid-of-noimport_playername) for details

Thanks for the report, it seems the default I chose (100 names per batch) is sometimes too large in cases, I'll reduce it.

**Comment by SullyTheUnusual** [comment]
You're right about the log size, I guess it only displayed output for the ones not found.

**Comment by jomo** [comment]
It's possible that you're on DS-Lite or some other CGNAT, thus sharing the IP address with some others. Eventually you have some other plugins that are making requests to the API. Or you have previously ran it, managed to get rate limited and were *still* rate limited when you started it again.

> it seems the default I chose (100 names per batch) is sometimes too large in cases, I'll reduce it.

Does this actually fix it? I doubt it does, because the rate limit is meant to limit the number of *requests* not the number of names, unless Mojang has gone completely retarded (which might be the case however).
Anyway, reducing the number of names per batch would actually raise the number of requests, resulting in faster hitting the rate limit.

-----

Are you catching HTTP 429s though? It should work if you catch the first one, wait a minute or two and try again.

**Comment by frymaster** [comment]
>Anyway, reducing the number of names per batch would actually raise the number of requests, resulting in faster hitting the rate limit.

That's what I would have thought, too!

However, they were hitting the problem on the very first request, and reducing the batch size to 50 resolved it for them. No, I don't understand it either.

**Comment by jomo** [comment]
Hmm @dinnerbone @KrisJelbring could you explain what's going on with your API? :)

**Comment by KrisJelbring** [comment]
You are limited to 100 profiles per request and 600 requests per 10 minutes. Since this is a completely open API (no API keys etc.) we have to enforce a limit in order to prevent abuse.

**Comment by frymaster** [comment]
I can only assume that the issue this guy had was entirely coincidental with me reducing the number of requests per batch. I'll double check that, then revert the change

On 16 February 2015 12:49:08 GMT+00:00, Kristoffer Jelbring <notifications@github.com> wrote:
>You are limited to 100 profiles per request and 600 requests per 10
>minutes. Since this is a completely open API (no API keys etc.) we have
>to enforce a limit in order to prevent abuse.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/LogBlock/LogBlock/issues/576#issuecomment-74503498

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by frymaster** [comment]
Confirmed that the query that was failing for OP worked for me. I must assume that IP had reached the request limits coincidentally, and so the change I made to the batch size was also made coincidentally with the rate limiting expiring/

@KrisJelbring thanks for confirming the limits, much appreciated

**Comment by SullyTheUnusual** [comment]
This issue has popped up again.

Using build #18 and it's throwing the 429 HTML response code again:

http://pastebin.com/GUXxG0Ni

**Comment by frymaster** [comment]
>Still a problem, though.

Nothing we can do, I'm afraid.  The limits are what the limits are

**Comment by jomo** [comment]
Well you could do this:
> Are you catching HTTP 429s though? It should work if you catch them, wait a minute or two and try again.

**Comment by SullyTheUnusual** [comment]
Catching the exception and re-polling periodically would be preferable to having to restart the entire server.

Thanks for your work on this!  :)
