### ISSUE TITLE
NPE if starting new Logblock with no DBs

### ISSUE THREAD

**Issue by andrewkm** [LogBlock/LogBlock#578]
If starting logblock on new builds with no DB entries NPE in console:

http://pastie.org/pastes/9952469/text

Afterwards it creates the tables just fine since first startup.

**Comment by frymaster** [comment]
Hi,

can you paste the full startup log? Did you have a pre-existing logblock config or were you starting from scratch?

**Comment by frymaster** [comment]
I have a hypothesis

Logblock does two things when starting up. It checks it the database schema needs updated, and it checks if there are missing tables, in that order.  If you have a pre-existing config, which has a version number in it which is older than the current database schema version, it will try to update the tables which, at that point, don't exist.

Does that match your circumstances?  If so, I'm loath to actually change anything - swapping the order around would just lead to the updater erroring over trying to add already added columns etc.

**Comment by andrewkm** [comment]
Sorry for my late reply.

Yes I had a pre existing logblock configuration.
I simply deleted the DB and recreated an empty one. Afterwards this NPE was generated.
After another restart, the problem was solved and never happened again. Basically something that isn't much of an issue, other than for users who first start this plugin with a pre existing config and no tables.

**Comment by andrewkm** [comment]
The circumstances you have mentioned are indeed my circumstances.
I (every few months) delete the DB and recreate a fresh one. If this happens once more in the future I will respond to this ticket once more, but I believe it can be closed if you like. Just thought I would mention it in case it is something that would concern you :)

Cheers!

**Comment by frymaster** [comment]
Yeah, I think it's only if you wipe the DBs **and** update logblock at the same time.  It's not a big deal, but you could avoid it by deleting the "version" string from the config, which is the thing which the updater triggers on - the tag will be re-created as the current version, and no DB update procedure will be run
