### ISSUE TITLE
MySQL Database Locked

### ISSUE THREAD

**Issue by MarioC6** [LogBlock/LogBlock#590]
MySQL Database is being locked when new players join my server seen with the following console error in the pastebin link:
http://pastebin.com/NJenS154

I'm not sure if this is what fixes it (according to other sources who tell me) I should change the max_connections to equal 100 for the LogBlock config.yml but seeing that I don't have that option
in my config how do I add it or how should I fix this error?
I referred to the max_connections line from the link below:
http://goo.gl/WkTh9q

Any help is greatly appreciated!
Thanks,
Mario

**Comment by frymaster** [comment]
Hi,

Upping the max connections wouldn't solve that error anyway, but just so you know: That page has config options for *MySQL*, not for LogBlock.  I also don't advise using them; it's out of date, and in some places, wrong.

In any case, this isn't a LogBlock error:

1:41:20 PM CONSOLE: WARN]: at ch.dragon252525.**frameprotect**.util.**SQLite**.insertOrUpdatePlayer(SQLite.java:105)

The error is in the plugin called "frameprotect" and it's having problems accessing its SQLite (local file, not MySQL) database
