### ISSUE TITLE
Logblock database crawling massively slowed down since UUID implementation.

### ISSUE THREAD

**Issue by mibby** [LogBlock/LogBlock#591]
@frymaster 
Since updating LogBlock to the latest dev builds with UUID support, looking up logs for users has greatly slowed down. Both in looking up all logs and rolling back users for 60 days. It takes ~30 seconds to show logs / start a rollback, then completes instantly. 

Prior to updating, I was using this branch for months and did not experience any issues or slowdown. https://github.com/DarkArc/LogBlock/tree/worldedit-6.0.0-pretty-chat

Currently using LogBlock dev 238 (http://ci.md-5.net/job/LogBlock/238/) as of commit https://github.com/LogBlock/LogBlock/commit/df8bc51437bf0023dc1b8fe31a50daeb653ad2fb
MySQL, database is ~3.3GiB in size.
```
consumer:
  timePerRun: 1000
  useBukkitScheduler: true
  forceToProcessAtLeast: 500
  queueWarningSize: 2000
  fireCustomEvents: false
  delayBetweenRuns: 0
lookup:
  dateFormat: MM-dd HH:mm:ss
  linesLimit: 1500
  defaultTime: 30 minutes
  defaultDist: 20
  linesPerPage: 15
```
Apologies, but other than what I have experienced comparing the latest source compilation against the branch I had been using, I'm not sure what else could be causing the database log lookup slowdown. 

Perhaps you could look into adding a command to check the lookup query speed, similar to LWC's admin report command? Anything that could help diagnose and debug where the slowdown may be coming from? 

Example of '/lwc admin report' command output.
```
[01:40:41] [Server thread/INFO]: LWC Report
[01:40:41] [Server thread/INFO]:   Version: 4.5.0
[01:40:41] [Server thread/INFO]:   Running time: 1 hour 40 minutes 27 seconds
[01:40:41] [Server thread/INFO]:   Players: 15/512
[01:40:41] [Server thread/INFO]:   Item entities: 46/1601
[01:40:41] [Server thread/INFO]:   Permissions API: VaultPermissions
[01:40:41] [Server thread/INFO]:   Currency API: VaultCurrency
[01:40:41] [Server thread/INFO]:  
[01:40:41] [Server thread/INFO]:  ==== Modules ====
[01:40:41] [Server thread/INFO]:   LWC v4.5.0-SNAPSHOT -> 48 registered modules
[01:40:41] [Server thread/INFO]:  
[01:40:41] [Server thread/INFO]:  ==== Database ====
[01:40:41] [Server thread/INFO]:   Engine: MySQL
[01:40:41] [Server thread/INFO]:   Protections: 33,202
[01:40:41] [Server thread/INFO]:   Queries: 405 | 0.07 / second
[01:40:41] [Server thread/INFO]:  
[01:40:41] [Server thread/INFO]:  ==== Cache ==== 
[01:40:41] [Server thread/INFO]:   Usage: 44.27%  ( 33202/75000 [75000+0] )
[01:40:41] [Server thread/INFO]:   Profile: 
[01:40:41] [Server thread/INFO]:     isKnownNull: 1,572,610 (260.93 / second)
[01:40:41] [Server thread/INFO]:     getProtection: 180,130 (29.89 / second)
[01:40:41] [Server thread/INFO]:     addKnownNull: 62,050 (10.30 / second)
[01:40:41] [Server thread/INFO]:     addProtection: 33,282 (5.52 / second)
[01:40:41] [Server thread/INFO]:     removeProtection: 23 (0.00 / second)
```

**Comment by frymaster** [comment]
Thanks for reporting

Does this go fast or slow?

"/lb all limit 1000"

On 28 February 2015 09:45:19 GMT+00:00, mibby <notifications@github.com> wrote:
>@frymaster 
>Since updating LogBlock to the latest dev builds with UUID support,
>looking up logs for users has greatly slowed down. Both in looking up
>all logs and rolling back users for 60 days. It takes ~30 seconds to
>show logs / start a rollback, then it completes instantly. 
>
>Prior to updating, I was using this branch for months and did not
>experience any issues or slowdown.
>https://github.com/DarkArc/LogBlock/tree/worldedit-6.0.0-pretty-chat
>
>Currently using LogBlock dev 238 (http://ci.md-5.net/job/LogBlock/238/)
>as of commit
>https://github.com/LogBlock/LogBlock/commit/df8bc51437bf0023dc1b8fe31a50daeb653ad2fb
>MySQL, database is ~3.3GiB in size.
>```
>consumer:
>  timePerRun: 1000
>  useBukkitScheduler: true
>  forceToProcessAtLeast: 500
>  queueWarningSize: 2000
>  fireCustomEvents: false
>  delayBetweenRuns: 0
>lookup:
>  dateFormat: MM-dd HH:mm:ss
>  linesLimit: 1500
>  defaultTime: 30 minutes
>  defaultDist: 20
>  linesPerPage: 15
>```
>Apologies, but other than what I have experienced comparing the latest
>source compilation against the branch I had been using, I'm not sure
>what else could be causing the database log lookup slowdown. 
>
>Perhaps you could look into adding a command to check the lookup query
>speed, similar to LWC's admin report command? Example of '/lwc admin
>report' command output.
>```
>[01:40:41] [Server thread/INFO]: LWC Report
>[01:40:41] [Server thread/INFO]:   Version: 4.5.0
>[01:40:41] [Server thread/INFO]:   Running time: 1 hour 40 minutes 27
>seconds
>[01:40:41] [Server thread/INFO]:   Players: 15/512
>[01:40:41] [Server thread/INFO]:   Item entities: 46/1601
>[01:40:41] [Server thread/INFO]:   Permissions API: VaultPermissions
>[01:40:41] [Server thread/INFO]:   Currency API: VaultCurrency
>[01:40:41] [Server thread/INFO]:  
>[01:40:41] [Server thread/INFO]:  ==== Modules ====
>[01:40:41] [Server thread/INFO]:   LWC v4.5.0-SNAPSHOT -> 48 registered
>modules
>[01:40:41] [Server thread/INFO]:  
>[01:40:41] [Server thread/INFO]:  ==== Database ====
>[01:40:41] [Server thread/INFO]:   Engine: MySQL
>[01:40:41] [Server thread/INFO]:   Protections: 33,202
>[01:40:41] [Server thread/INFO]:   Queries: 405 | 0.07 / second
>[01:40:41] [Server thread/INFO]:  
>[01:40:41] [Server thread/INFO]:  ==== Cache ==== 
>[01:40:41] [Server thread/INFO]:   Usage: 44.27%  ( 33202/75000
>[75000+0] )
>[01:40:41] [Server thread/INFO]:   Profile: 
>[01:40:41] [Server thread/INFO]:     isKnownNull: 1,572,610 (260.93 /
>second)
>[01:40:41] [Server thread/INFO]:     getProtection: 180,130 (29.89 /
>second)
>[01:40:41] [Server thread/INFO]:     addKnownNull: 62,050 (10.30 /
>second)
>[01:40:41] [Server thread/INFO]:     addProtection: 33,282 (5.52 /
>second)
>[01:40:41] [Server thread/INFO]:     removeProtection: 23 (0.00 /
>second)
>```
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/LogBlock/LogBlock/issues/591

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by mibby** [comment]
"/lb all limit 1000" is near instant.

Looking up logs with player specific names is what seems to take forever (~30 seconds) Example, "/lb lookup player mibby time 60 days" and rollback commands such as "/lb rb player mibby time 60 days".

**Comment by frymaster** [comment]
execute the following SQL:

``CREATE INDEX playername ON `lb-players` (playername);``

Basically, when player names were no longer unique, I dropped the unique index on the table, forgetting, of course, that they're still a really important querying criteria and so need a non-unique index instead.

Does that solve your problem? Also, how many rows is your player table?

**Comment by mibby** [comment]
Not sure if I ran it correctly. Executed the SQL command on the lb-players table outputted;
```
SQL query:

CREATE INDEX playername ON `lb-players` (playername)

MySQL said: Documentation
#1061 - Duplicate key name 'playername' 
```

I have 4672 rows in lb-players.

Testing again to see if the command improved anything, it seems there is now only a delay of about 3-5 seconds instead of 20.

**Comment by frymaster** [comment]
Fixed - *I think* - in 143bcf6d762dca955e614c9d38f84a8d0177b62b

This will add the index I just asked you to add, but *shouldn't* error out if it's already there

I'm fairly sure this was your issue - it certainly was **an** issue - but reopen this bug if you have further problems, and we'll try something else

**Comment by mibby** [comment]
Alright, thanks for your help. I'll let you know if I run into any other slowdown issues. :)

**Comment by mibby** [comment]
Just confirming with the new build that lookup does indeed seem to be fixed. No more long duration. The only delay (~2-5 seconds) comes from how many records it is querying, which I compared by looking up logs for a player who actively mine for 5 and 60 days against someone who does not mine at all.
