### ISSUE TITLE
unable to clear table entries

### ISSUE THREAD

**Issue by frizzbee30** [LogBlock/LogBlock#593]
Hi, very minor error I get in console http://pastebin.com/NdaxRnFw I've check the worlds (and names) tally to the config for world clearing here http://pastebin.com/4qq775wc I'm guessing that the tables dont match the configured items? Am I correct? Or is it another config error. otherwise it works great :) Thanks

**Comment by frymaster** [comment]
``world Survival Map``

It's not liking the spaces.  Try ``world "Survival Map"``

**Comment by frizzbee30** [comment]
Thanks, that's great. I wasn't sure about the spaces, but it seemed to be logging ok with the name so figured the database clear would be ok. Thank you for the rapid reply!

**Comment by frizzbee30** [comment]
should have looked at the tables, it had been converted to survival_map in database  :)  thanks for the help
