### ISSUE TITLE
SQL Error when making SQL Table UUID. 

### ISSUE THREAD

**Issue by CLGREEN94** [LogBlock/LogBlock#596]
Hello, 

When I make a test server, LB trows an error when it trys to log the UUID. 

http://pastebin.com/hmTHLgwN

Can you please provide the SQL code to make the UUID table automatically :) 

Thanks 

Callum.

**Comment by frymaster** [comment]
I take it you're connecting a fresh minecraft install to a pre-existing database?

Stop the server, set the version in the config file to "1.83" and restart and it should update as necessary (if you know for a fact it was using an even earlier logblock version, put that in if you know it)

**Comment by frymaster** [comment]
No response

**Comment by CLGREEN94** [comment]
Sorry, I have been off due to University work slowly killing me off. 

I think that fixed it. It was for another one of my staff members I just logged the issue and give him the response but he has also been off with work. if it does not fix the issue I will let you know. 

Sorry once again and thanks. 

- Callum (CLGREEN)
