### ISSUE TITLE
Cauldron/Mod support

### ISSUE THREAD

**Issue by Time6628** [LogBlock/LogBlock#597]
Hello! 
Could you add more support for mods? For example, the IronChest mod isn't logged by LogBlock. I really love LogBlock but I can'y use it on my modded server :cry:. Maybe make a cauldron version of it like Prism does? 
Thanks,
-Time

**Comment by frymaster** [comment]
Personally I don't have the time to commit to the amount of work that would take, given I don't have a personal need for that.  I can't speak for other devs; I'll leave this open for a week then close it if no one chips in

**Comment by Time6628** [comment]
:disappointed: Well, if anyone does decide to make a port of LogBlock to cauldron, please tell me because I would love to test it out for them :smile: 
Thanks anyways and keep loggin' those blocks!
-Time

**Comment by frymaster** [comment]
Will do :)
