### ISSUE TITLE
The table 'lb-Survival1' is full

### ISSUE THREAD

**Issue by MuroHasegawa** [LogBlock/LogBlock#599]
Getting this when someone builds or breaks in my worlds, and I don't think that the table is actually full.

http://pastebin.com/gmSGs2HY

**Comment by frymaster** [comment]
the most likely cause is that the disk the database writes to is full - can you check that?

**Comment by MuroHasegawa** [comment]
I talked with the server host, the mysql server was failing thus causing that error.
