### ISSUE TITLE
Not logging items taken/placed in trapped chests

### ISSUE THREAD

**Issue by Her-Craving** [LogBlock/LogBlock#609]
This might be fixed in a development version, but after waiting days for a response in the comments section, nobody said anything.

**Comment by frymaster** [comment]
Comments section of what?

Anyway, please try the latest dev version and report back.  Apart from anything else, only the dev snapshots will record UUIDs, and the longer you leave it, the more people will have changed their name ([FAQ entry](https://github.com/LogBlock/LogBlock/wiki/FAQ#warning-logblock-updater-playername-not-found---giving-uuid-of-noimport_playername))

**Comment by Her-Craving** [comment]
Is the latest dev build relatively stable? I'm referring to the comment section on the bukkit dev page.

**Comment by frymaster** [comment]
> I'm referring to the comment section on the bukkit dev page.

Ah, I don't get notifications about that so I tend not to notice that

>Is the latest dev build relatively stable?

In the sense of "liable to have bugs", it's likely to have less bugs than the last release version - the parameter parsing code got a massive cleanup, it's updated to work with newer versions of worldedit, there's many logging improvements (especially in regards to projectiles, explosions, trapped chests, and fire), and of course it will track UUIDs now

**Comment by Her-Craving** [comment]
Since I'm a total noob, how do I download the newest dev build?

**Comment by Her-Craving** [comment]
Nvm I found the jenkins page

**Comment by frymaster** [comment]
Cool - are your trapped chests being logged now?

**Comment by Her-Craving** [comment]
Yes, and somehow it now shows me what were previously put into and taken out of them before that version was even added.
