### ISSUE TITLE
Logblock and AsyncWorldEdit

### ISSUE THREAD

**Issue by MyNameIsWeird** [LogBlock/LogBlock#611]
it says on the website that this plugin can log worldedit, and it worked on a server I had a few months ago, but when I installed AsyncWorldEdit, along with WorldEdit and LogBlock, on a server that I am staff on, it didnt log worldedit. I have logging WorldEdit enabled in the config, and I am not getting any errors.

**Comment by LefsFlare** [comment]
You need to enable WorldEdit logging in every single world. It's separate logging configurations for each different world.

**Comment by frymaster** [comment]
I should also point out you need the dev snapshots to log the latest versions of worldedit
