### ISSUE TITLE
LogBlock clearlog not working (No Space in world name)

### ISSUE THREAD

**Issue by cburcus** [LogBlock/LogBlock#612]
So i have a pixelmon server and i installed logblock as it seems to be faster than core protect. Anyways, it does everything i want it to do and it's great, but i can't automatically clear the logs.

First, in the config file i have it set to automatically clear the logs but somehow it never does it.

Config: http://pastebin.com/bDdX21yB

If i run the commant /lb clearlog before 3 days all, in-game it works just fine.

I was going to put it as a command to run from the console everyday since the config won't do the trick but i can't seem to get it to work. Most people who have this issue is because their world name is made up of at least two words. Mine is the default "world". The following is the command i enter in the console and the result i get.

lb clearlog world "world" before 3 days all

[19:50:40] [Server thread/INFO]: Wrong count of arguments for 'world'

Any help will be greatly appreciated. I don't want to have to perform this command manually every day.

**Comment by Mahagon** [comment]
Your config doesnt seem to be correctly formatted 

Paste your config here: http://yaml-online-parser.appspot.com/ 
It will help you debugging.

world "world" before 3 days all

is working for me with the latest dev build.

**Comment by cburcus** [comment]
Yes i have used the yaml-online-parser. The only reason it shows broken when you post it from pastebin is because i modified the mysql info in pastebin so it makes it all weird.

Could it be possible that it's my server configuration? I mean it logs everything properly and i can run the "lb clearlog before 3 days" command when i'm logged in as a player. I just can't run it from the console and the automatic command either runs but it gives the same error or it doesn't run at all.

I have a pixelmon server with a bunch of other plugins like towny, grief prevention, etc

**Comment by frymaster** [comment]
The command parser was updated recently to resolve issues involving quoted values, if your ``/version logblock`` doesn't say "build 244" or newer, please try downloading a dev build from http://ci.md-5.net/job/LogBlock/changes

(if it doesn't mention a build number at all, it's too old)

**Comment by Time6628** [comment]
If he's running a pixelmon server, that means he is on 1.7.10. So, I don't think he can use the latest versions. @Frymaster

**Comment by frymaster** [comment]
Minimum required server version is 1.7.3

Apart from armour, we should be able to support all 1.8 features without affecting compatibility

**Comment by frymaster** [comment]
In any case, no response, closing.

Please reopen this issue if you are still having problems
