### ISSUE TITLE
Logged World Issue

### ISSUE THREAD

**Issue by ShadowRanger** [LogBlock/LogBlock#614]
Hi there,

So the other day I decided to reset the end world on my server by deleting the old one and allowing a new one to be created. I also deleted the corresponding MySQL tables of the world for LogBlock, thinking that it would be the right thing to do. It ended up turning out that I was wrong. For some reason I am no longer able to use LogBlock with the end world in the loggedWorlds list in the config. I have tried removing it, restarting the server, then adding it back and restarting the server among many other things but I can't seem to get it to work. Here is the console output I am getting:

13.05 20:11:36 [Server] INFO HikariCP pool LogBlock-Connection-Pool is shutting down.
13.05 20:11:36 [Server] INFO Disabling LogBlock v1.94-dev-SNAPSHOT (build #256)
13.05 20:11:36 [Server] INFO Enabling LogBlock v1.94-dev-SNAPSHOT (build #256)
13.05 20:11:36 [Server] ERROR Error while loading: Table '`-`.`lb-world_the_end`' already exists
13.05 20:11:36 [Server] INFO Creating table lb-world_the_end.
13.05 20:11:36 [Server] INFO HikariCP pool LogBlock-Connection-Pool is starting.
13.05 20:11:35 [Server] INFO Connecting to -@jdbc:mysql://-/-...
13.05 20:11:35 [Server] INFO HikariCP pool LogBlock-Connection-Pool is shutting down.
13.05 20:11:35 [Server] INFO Waiting for consumer ...
13.05 20:11:35 [Server] INFO Disabling LogBlock v1.94-dev-SNAPSHOT (build #256)

(I removed the private information including MySQL IP... etc from this log and replaced them with -)

As you an see it'ss aying that the table already exists, even know it actually doesn't.

Any ideas what's going wrong? Thanks in advance.

**Comment by frymaster** [comment]
The server log is missing a ton of info, and it's also running backwards in time for some reason. Can you post the raw logs please (edit out the MySQL server details if you think you need to, but I'd appreciate it if you do something like `<server>` rather than just a dash, just to make it more readable

**Comment by ShadowRanger** [comment]
Wow okay so just as I was going to generate a new fresh log file for you it started working now. I think it may have been something on my side with the MySQL server. Sorry about that. Thanks though.

**Comment by frymaster** [comment]
Glad it's working :)
