### ISSUE TITLE
Rollback Restrictions

### ISSUE THREAD

**Issue by ViscousSummer88** [LogBlock/LogBlock#618]
The rollback restrictions are not working correctly; Users who have access to logblock.rollback are able to run the command correctly however if they do not have access to logblock.ignoreRestrictions and restrictions are enabled in the config.

Users are unable to use the rollback command without being told they are going over the restriction limit when in actual fact the command they are running meets the restrictions set in the config.

**Comment by frymaster** [comment]
What's the output of ````/version logblock````?

Can you give a specific example that's going wrong?

**Comment by ViscousSummer88** [comment]
Version 1.94, Build 256.

Restrictions are set to 50.
When someone who does not have the restriction bypass permission they are faced with the message stating they can only rollback in an area less than 50 however they are typing /lb rb player bob time 10 mins area 20

**Comment by ammaraskar** [comment]
Could you paste your config.yml

**Comment by Brokkonaut** [comment]
Cannot reproduce
