### ISSUE TITLE
Mobs killed with a Fire Aspect/Flame weapon report FIRE_TICK instead of the player name

### ISSUE THREAD

**Issue by redwallhp** [LogBlock/LogBlock#622]
If a player kills a sheep/horse/cow/whatever using a fire weapon, such as a Fire Aspect sword, they can trivially time their attacks so their misdeed is not shown in LogBlock's kill list.

Steps to reproduce:
1. Acquire a Fire Aspect sword
2. Hit an animal 2-3 times, pausing briefly between each hit, so the fire effect reduces its life to zero instead of the direct sword damage.
3. Check /lb kills

Proposed solution: If a player hits a mob with a weapon, and the mob subsequently dies by fire within the time frame of a Fire Aspect debuff, it should be tracked as a kill by the player.

**Comment by frymaster** [comment]
tracking the mobs is more problematic than it could be

the only foolproof way to track a mob is by UUID, but there's no way to retrieve a mob's object from its UUID without getting a list of all entities in the world and iterating through

I can use a weak reference to the actual mob entity object, but that will become invalid under certain circumstances

Basically, if this gets added it will **not** be foolproof.  Causing the chunk to unload will cause LogBlock to forget about the flaming mob, which will then burn to death when the chunk is loaded again. It's better than nothing, though

**Comment by Time6628** [comment]
Couldn't you assign the mob a number? Like when a mob is attacked by a player, assign it a number so logblock knows who attacked it. idk if that will work as well, just throwing something out there lol.

**Comment by frymaster** [comment]
you have the same problem - if they can get the chunk to unload before the mob is due to burn to death, when the timer expires the mob is nowhere to be found

this is still worth having - logging *most* is better than none
