### ISSUE TITLE
Support for logging entities. (Item frames, armor stands, & painting?)

### ISSUE THREAD

**Issue by mibby** [LogBlock/LogBlock#623]

**Comment by frymaster** [comment]
There are issues tracking at least two of those but I'm at work so I'll link later

One thing I *will* say is that armor stands are likely to be the last of these added, since that means moving to the spigot fork of Bukkit, and while that's something that needs to happen, I'd like to keep compatability for as long as possible

It's not that I'd hold back on adding it, just it'd be the last in the queue

**Comment by mibby** [comment]
Understandable. :) 

Looking forward to the day those items are loggable as they are the remaining things users complain about that get griefed.

**Comment by mibby** [comment]
@frymaster Any update to adding support for item frames, armor stands, and paintings for logging and rollback support? I'd hate to have to switch to CoreProtect, as I find logblock to be the the best out of all the logging plugins available. But it is becoming a nuisance to fix these griefed items manually, so support would be great.

**Comment by RoboMWM** [comment]
In other words, it'll never be added here.

**Comment by mibby** [comment]
Any possible update for entity logging this year @frymaster ? :(

**Comment by mibby** [comment]
The day logblock ever gets proper tile / entity logging for item frames and armor stands will be a joyous day, if it shall ever come. :(

**Comment by mibby** [comment]
Yearly bump to inquiry if LogBlock will ever have entity logging support. :)

**Comment by mibby** [comment]
@Brokkonaut Any progress at all in being able to log and rollback entities? (item frames, armorstands, etc.)

**Comment by Brokkonaut** [comment]
No, I did not have time for it yet

**Comment by mibby** [comment]
Alright. When you do, let me know and I can help do some testing. :)

**Comment by Brokkonaut** [comment]
If you want you can try this branch: https://github.com/LogBlock/LogBlock/tree/entity-logging-v2
You will have to compile it yourself for testing - Currently implemented is logging + rollback for creation/killing(destroying) of most entities and armor stand/item frame equipment changes.

You have to use the parameter "entities" in the querys:
/lb entities area 10 coords
or:
/lb rollback entities area 10

Filtering for entity types or actions is planned but currently not implemented, configuration what entities should be logged can be done in the world config for each world.

**Comment by Brokkonaut** [comment]
Entity logging is now added to logblock (paintings cannot be rolled back correctly because of worldedit but armor stands + item frames should work

**Comment by Brokkonaut** [comment]
are there any exceptions? and what worldedit/spigot(paper) version are you using?

**Comment by mibby** [comment]
@Brokkonaut I was using Paper dev 489 and WorldEdit dev 3997.

Does entity logging rely on having worldedit logging enabled?

**Comment by Brokkonaut** [comment]
worldedit installed yes, worldedit logging enabled no (i recommend not to use worldedit logging)

**Comment by Brokkonaut** [comment]
what command do you use for lookup?

**Comment by mibby** [comment]
The standard logblock tool and toolblock. Staff were trying to interact with item frames and armor stands to see if they could get logs to show up. It could have been due to the latest worldedit API changes if required to function. 

I'll update to the latest LogBlock dev build and give it another try.

**Comment by Brokkonaut** [comment]
you have to use a tool (or command) in entity mode - for example `/lb entities area 10` or for the toolblock `/lb tb entities` (reset to normal with `/lb tb default`) - for rollback use for example `/lb rb entities area 10 entity sheep`
