### ISSUE TITLE
Spawner type?

### ISSUE THREAD

**Issue by L4BORG** [LogBlock/LogBlock#627]
Log block doesn't log/know/rollback spawner types?

**Comment by frymaster** [comment]
Yeah, right now LB doesn't log NBT metadata for anything (spawners, command blocks, enchanted / named items)

**Comment by Brokkonaut** [comment]
Added in https://github.com/LogBlock/LogBlock/commit/58e5cdf890301951b401394bd92a82b02cd26ef1
