### ISSUE TITLE
Version numbers about to go higher than the updater can parse

### ISSUE THREAD

**Issue by frymaster** [LogBlock/LogBlock#629]
Currently the database updater uses string comparisons to compare whether a version is higher than another.  This worked when we were using 1.xy, as long as x and y were both single-digit numbers

Unfortunately, we're at 1.95 right now. We either have to switch to something more sophisticated, or our next version has to be 2.0

There are libraries which can compare x.y.z version numbers... I suggest we use one of them, and before comparing, special-case something that says a version of the form 1.xy is actually 1.x.y.  Only downside is that for e.g. version 1.10 we'd have to remember to put 1.10.0

**Comment by ammaraskar** [comment]
>There are libraries which can compare x.y.z version numbers... I suggest we use one of them, and before comparing, special-case something that says a version of the form 1.xy is actually 1.x.y. Only downside is that for e.g. version 1.10 we'd have to remember to put 1.10.0

eh? Do we need a library? Sounds simple to code.
