### ISSUE TITLE
idea] Rollback-as-ghost

### ISSUE THREAD

**Issue by rautamiekka** [LogBlock/LogBlock#637]
While I were checking for possible X-ray, an idea hit me which would make X-ray finding easier and faster: `rollback as ghost` parameter or command (`rollback-ghost`; could be shortened to `rbag` or `rbg`), which gathers the matches and rolls them as usual, but as partially transparent (and preferably a little differently colored), fully non-solid blocks to easily see what blocks were destroyed.

Also, this'd introduce a new logged data which tells other LB rollers when someone with the ability used the feature, which reads like this (assuming `coords` parameter):

```
2015-07-29 10:38:18 rautamiekka rolled back as ghost cobblestone at 137:11:-272
```

If fully non-solid is impossible, then keep it solid, but also introduce new data which reads like this when the same blocks are queried again (assuming `coords` parameter):

```
2015-07-29 10:38:18 rautamiekka destroyed cobblestone (rollback-as-ghost) at 137:11:-272
```

**Comment by frymaster** [comment]
That kind of client-side display isn't possible with a bukkit mod - but check out https://github.com/totemo/watson (scroll down for the screenshots) - it's a clientside mod that interprets your queries and displays them in the world

**Comment by rautamiekka** [comment]
The logged data would be useful, especially when combined with that plugin.

**Comment by Brokkonaut** [comment]
#20 But I don't think its possible without client mods
