### ISSUE TITLE
Setting up Database in Config

### ISSUE THREAD

**Issue by Kgamer5000** [LogBlock/LogBlock#640]
So I just got logblock, and I found the config and mysql information, and put it in. However, when I start the server and do /lb, it still says no database is connected. Any help? I use BisectHosting and can post my config if needed.

**Comment by frymaster** [comment]
Please post the startup log from your server

**Comment by Kgamer5000** [comment]
Nevermind it, I really wanted to use Prism, but it wasn't updated. Log block was too difficult, so I'll just use CoreProtect. Simply solved.

**Comment by frymaster** [comment]
Can I ask what you found difficult, so that we might improve it?

**Comment by frymaster** [comment]
No response
