### ISSUE TITLE
Tools generated through /lb tool will cover the previous handing item

### ISSUE THREAD

**Issue by jessefjxm** [LogBlock/LogBlock#646]
For example, if you're handing a enchanted pickaxe while typing the /lb tool command, you'll get a LBTool just right in your hand, which means the previous item will be lost. Even if I type /lb tool off, it won't give me back that item. Hope this can be fixed, or just move the handing item to other place in inventory. :)

Spigot 1.8.7, LB 1.94

**Comment by Brokkonaut** [comment]
This is fixed
