### ISSUE TITLE
DoorInteract missing logging data from all 1.8 fence gate and door variants.

### ISSUE THREAD

**Issue by mibby** [LogBlock/LogBlock#650]
LogBlock dev 269

LogBlock does not log interactions from any of the minecraft 1.8 variant fence gates and doors. Spruce, birch, jungle, acacia, and dark oak. It logs placement but not the opening/closing moved interaction.

As a side note, oak fence gates logs opening and closing, but oak doors only log moved. Is it not possible to log open and close for doors too like the gates? Also, is it not possible to get door logs from both blocks? The top part and bottom part of the door both log their own interaction based on whether the person clicked on the top or bottom part of the door.

**Comment by mibby** [comment]
Still waiting on proper 1.8 support. :(

**Comment by Brokkonaut** [comment]
Fixed in the 1.13 update
