### ISSUE TITLE
[SERIOUS] End Crystal explosion not logged

### ISSUE THREAD

**Issue by spetznack** [LogBlock/LogBlock#664]
I guess this is a feature request, since the End Crystal is not a block - but to not be able to rollback end crystal explosions is a big issue, just like the minecart-tnt was. For now it seems like the only way to protect my server from this - is to not allow players to place End Crystal at all. Which is not optimal because we want players to be able to respawn the enderdragon and some players wants to use this new entity as decoration :/ 

1) Can we log End Crystal explosions using logblock?
2) Is it possible to log who attacked the End Crystal to make it explode? 
3) Can LogBlock log who placed the End Crystal?

**Comment by Phoenix616** [comment]
My [PR 669](https://github.com/LogBlock/LogBlock/pull/669) adds a seperate log and config entry for the ender crystal but for now you can log the eplosion by enabling the MISCEXPLOSION in the world's config.

For your other questions it would require us to implement new features like caching of the clicks (the player who clicked currently can't be queried with Bukkit's EntityExplodeEvent) and for placement to find a way of properly implementing entity/pseudoblock logging.

**Comment by spetznack** [comment]
That's awesome Phoenix :D I actually didn't think of MISCEXPLOSION and enabling this does at least make it possible to roll back damage done by the End Crystal explosion! 

If for example @md-5 @frymaster or @ammaraskar would have a peek at this, hopefully your PR can be reviewed :3

It would be very useful if LogBlock could log (and roll-back) placement or changes done to place-able entities like item-frames, armor-stands, maps and so on. Though this sounds complicated and if implemented this will probably be a part of LogBlock that will mess things up when new Minecraft versions comes out? :S
