### ISSUE TITLE
Logblock double chest issue

### ISSUE THREAD

**Issue by killerkoda13** [LogBlock/LogBlock#676]
Ive been using logblock and I noticed that double chests have different logs per each chest. Is there any way this could be fixed or added?

**Comment by alekso56** [comment]
If someone did a lot of checks to account for the fact that a chest nearby would equal a double chest, sure.
else you are going to have to deal with the way minecraft operates. (one entity for each block, render if two are near)

**Comment by killerkoda13** [comment]
Coreprotect does it... And it works just fine.
