### ISSUE TITLE
spigot 1.10.2 and LB build 274 insertion issue in MySql

### ISSUE THREAD

**Issue by frizzbee30** [LogBlock/LogBlock#678]
Hi, intermittently getting this error in console, I'm wondering if it's just the new blocks that LB is struggling to deal with?

http://pastebin.com/wfXNaxxh

Thanks :)

**Comment by frymaster** [comment]
`Data truncation: Out of range value for column 'z' at row 1`
`INSERT INTO `lb-vanilla` (date, playerid, replaced, type, data, x, y, z) VALUES(FROM_UNIXTIME(1467055788), 55, 54, 54, 0, -16000019, 14, -16000022)`

See [this](https://github.com/LogBlock/LogBlock/wiki/FAQ#mysqldatatruncation-data-truncation-out-of-range-value-for-column-x-at-row-1) - tl;dr the co-ordinates are bigger than the table is set up to record.  That FAQ tells you to change it to MEDIUMINT, but the values you're getting (16 million) are above even that - use INTEGER instead

**Comment by frizzbee30** [comment]
Thanks, I'm not a MySQL wizz, but can do basic usage. We host on an external MySQL db server with other plugins using the tables. Do these commands need running on the db server ?

What is odd, is that the world size hasn't changed, only the update to 1.10.2, 

thank you for your assistance.  :)

**Comment by frizzbee30** [comment]
run through SQL query.  Thanks
