### ISSUE TITLE
New column "world" in lb-players table

### ISSUE THREAD

**Issue by JohOply** [LogBlock/LogBlock#679]
Hi

Could you add a new column "world" which store current world where the player is ?

I think it could be nice :)

Thanks for reading!

**Comment by alekso56** [comment]
Why should that be added? 
it'd be a pain to update that every time the player moves to another world
and frankly will slow down everything more than needed >_> (in my opinion)

**Comment by JohOply** [comment]
It could be use to know where the player is easly. Maybe there is an event like "changeworld"?

**Comment by frymaster** [comment]
It wouldn't really slow things down, but I don't think it's appropriate for LogBlock, sorry :(

It's not related to tracking player actions, and database changes are enough of a pain to code that there needs to be a *really* good reason to make one
