### ISSUE TITLE
When you replace water with a sandstone slab, logs indicate that the block item is wood step rather than standstone step.

### ISSUE THREAD

**Issue by mibby** [LogBlock/LogBlock#685]
LogBlock dev 274
Paper (Spigot 1.10.2) dev 876

When you replace water with a sandstone slab, logs indicate that the block item is wood step rather than standstone step. Placing sandstone slabs down normally, logs show sandstone step correctly.

**Comment by Brokkonaut** [comment]
Fixed in 1.13
