### ISSUE TITLE
BlockExplodeEvent is not logged.

### ISSUE THREAD

**Issue by dscalzi** [LogBlock/LogBlock#698]
Hello, it appears that blocks destroyed by World#createExplosion() are not logged.
 
The fix for this is quite simple and quick, I would submit a PR but the code's not public. You need add a listener for the [BlockExplodeEvent](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/BlockExplodeEvent.html). This issue is quite important as **irreversable damage** can be done to servers who depend on LogBlock.

**Comment by md-5** [comment]
Feel free to open a pull request with the requisite changes
