### ISSUE TITLE
crazy errors

### ISSUE THREAD

**Issue by pookshuman** [LogBlock/LogBlock#700]
Getting a crazy amount of errors from logblock starting with 1.12

I don't know what any of it means, but LB is the only plugin I use that connects to mysql, which is mentioned in the log errors

Here is some of the server console https://pastebin.com/xPX2qwMC
And this is from the server logfile https://pastebin.com/hcDtbb33 https://pastebin.com/6VF2yLgW

version:
3:31:07 AM CONSOLE: [INFO] This server is running CraftBukkit version git-Spigot-5340a52-27b8bf9 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

plugins: (all up to date)
3:31:43 AM CONSOLE: [INFO] Plugins (27): CleanroomGenerator, dynmap, LuckPerms, WorldEdit, OpenInv, BukkitCompat, AntiAFKPlus, WorldBorder, Lockette, UUID, WorldGuard, Multiverse-Core, ProtocolLib, LogBlockQuestioner, Multiverse-Inventories, Multiverse-Portals, Vault, CBWrapper, Essentials, LogBlock, MCBans, VanishNoPacket, EssentialsProtect, EssentialsChat, EssentialsGeoIP, EssentialsAntiBuild, EssentialsSpawn

**Comment by md-5** [comment]
Some of those errors are not LogBlock.
I've fixed the one that is

**Comment by pookshuman** [comment]
cool, thank you

**Comment by pookshuman** [comment]
It looks like the latest build is showing as not stable, is it safe to use?

**Comment by mibby** [comment]
@pookshuman Unless you have lb-chat tables in your sql database (chat logging enabled), I would advise not updating to the latest dev build. It crashes the server and doesn't connect to the sql database when it can't update the tables due to it not existing.

https://github.com/LogBlock/LogBlock/issues/702
