### ISSUE TITLE
/lb command changes nick after execution if player with similar nick is online!

### ISSUE THREAD

**Issue by Gerolfing** [LogBlock/LogBlock#701]
For example player flor is offline and player Florence is currently online.
When I try to run
/lb lookup player flor 
or
/lb rollback player flor
plugin runs command for Florence . I simply can't run command for flor at the same time Florence is online.
Same thing happens with another similar nicks.

**Comment by md-5** [comment]
You should quote the player if you want an exact match

 /lb lookup player "flor"

**Comment by Gerolfing** [comment]
Thanks. I didn't know that.
