### ISSUE TITLE
Chest access logs are not being rolled back.

### ISSUE THREAD

**Issue by mibby** [LogBlock/LogBlock#703]
LogBlock dev 276
Spigot 1.12.1

ChestAccess is being logged properly but it is not being rolled back whatsoever. 

```
logging:
CHESTACCESS: true
```

* Place an item in a standard chest (ID 54)
* Attempt to rollback chestaccess / full logs
* Item still exists in chest

Same applies for taking an item out of a chest. It logs take/put properly but does not rollback the access.

```/lb rb player <player> chestaccess time 1 hour```

Also tried

```/lb rb player <player> chestaccess time 1 day```
```/lb rb player <player> time 1 day```

**Comment by mibby** [comment]
@md-5 Broke due to this spigot commit. https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/19507baf8b7903427bc3efab7118de6e7c1c931e#src/main/java/org/bukkit/craftbukkit/block/CraftBlockEntityState.java

**Comment by md-5** [comment]
Please stop tagging me in every issue you have

**Comment by mibby** [comment]
This issue was caused by you pulling that PR without warning plugin devs of the breaking change or  keeping any form of deprecated backwards compatibility. Seeing as though this breaks due to a spigot change and you are primarily the only one who has touched logblock in any recent time, I figured I'd give you the heads up.

**Comment by md-5** [comment]
Read the commit message before commenting.
This is more likely a case of logblock failing to use the API properly.

Every reasonable attempt was made at backwards compatibility, and the API is much more consistent and bug free as a result of those changes.
