### ISSUE TITLE
mysql update

### ISSUE THREAD

**Issue by seema84** [LogBlock/LogBlock#706]
can you please update mysql? i get the follow warning

Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification

**Comment by md-5** [comment]
#704 
1) its a warning
2) can be disabled by enabling ssl or setting useSSL=false

**Comment by seema84** [comment]
1. yes its a warning ... every minute and more (this is spam not a single warning)
2. "can be disabled by enabling ssl" if ssl is enabled i get this message too and the setting useSSL=false i can't find in logblock

**Comment by jwshields** [comment]
@md-5 Where do we put the useSSL=false?
The config doesn't allow us to add that to the JDBC URI and SSL is disabled on my MySQL instance.

**Comment by md-5** [comment]
https://dev.bukkit.org/projects/logblock?comment=1859

**Comment by seema84** [comment]
and why do you don't add a option in logblock for this?

**Comment by jwshields** [comment]
An option does not need to be added. A workaround has been given by the dev.
Thank you md-5

**Comment by seema84** [comment]
What workaround? Create a own fork and add this setting?

**Comment by seema84** [comment]
I thought, i only need on every plugin with this issue to add ?useSSL=false after the database name in the config?
example:   database: databasename?useSSL=false ?
