### ISSUE TITLE
Error appears in console when a player places a block past 8388607

### ISSUE THREAD

**Issue by zackatack108** [LogBlock/LogBlock#711]
I found a bug on my server where when a player was past the X or Z cord of 8388607 and placed a block an error message would appear involving logging the block placed.

Error Message:
12.06 02:50:44 [Server] ERROR Troublesome query: HikariPreparedStatementProxy@836090358 wrapping com.mysql.jdbc.JDBC42PreparedStatement@34fc0b37: INSERT INTO `lb-world` (date, playerid, replaced, type, data, x, y, z) VALUES(FROM_UNIXTIME(1528786244), 17, 0, 4, 0, 8388442, 22, 8388679)
12.06 02:50:44 [Server] ERROR SQL exception on insertion:
12.06 02:50:44 [Server] INFO java.sql.BatchUpdateException: Data truncation: Out of range value for column 'z' at row 1
12.06 02:50:44 [Server] INFO at sun.reflect.GeneratedConstructorAccessor286.newInstance(Unknown Source) ~[?:?]
12.06 02:50:44 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
12.06 02:50:44 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
12.06 02:50:44 [Server] INFO at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[custom.jar:git-Spigot-c3093ef-7e94e65]
12.06 02:50:44 [Server] INFO at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[custom.jar:git-Spigot-c3093ef-7e94e65]
12.06 02:50:44 [Server] INFO at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1163) ~[custom.jar:git-Spigot-c3093ef-7e94e65]
12.06 02:50:44 [Server] INFO at com.mysql.jdbc.PreparedStatement.executeBatchedInserts(PreparedStatement.java:1587) ~[custom.jar:git-Spigot-c3093ef-7e94e65]
12.06 02:50:44 [Server] INFO at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1253) ~[custom.jar:git-Spigot-c3093ef-7e94e65]
12.06 02:50:44 [Server] INFO at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970) ~[custom.jar:git-Spigot-c3093ef-7e94e65]
12.06 02:50:44 [Server] INFO at com.zaxxer.hikari.proxy.StatementProxy.executeBatch(StatementProxy.java:127) ~[LogBlock.jar:?]
12.06 02:50:44 [Server] INFO at com.zaxxer.hikari.proxy.HikariPreparedStatementProxy.executeBatch(HikariPreparedStatementProxy.java) ~[LogBlock.jar:?]
12.06 02:50:44 [Server] INFO at de.diddiz.LogBlock.Consumer$MultiBlockChangeRow.executeStatements(Consumer.java:969) ~[LogBlock.jar:?]
12.06 02:50:44 [Server] INFO at de.diddiz.LogBlock.Consumer.run(Consumer.java:633) [LogBlock.jar:?]
12.06 02:50:44 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [custom.jar:git-Spigot-c3093ef-7e94e65]
12.06 02:50:44 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [custom.jar:git-Spigot-c3093ef-7e94e65]
12.06 02:50:44 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
12.06 02:50:44 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
12.06 02:50:44 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
12.06 02:50:44 [Server] INFO Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Out of range value for column 'z' at row 1
12.06 02:50:44 [Server] INFO at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3971) ~[custom.jar:git-Spigot-c3093ef-7e94e65]
12.06 02:50:44 [Server] INFO at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909) ~[custom.jar:git-Spigot-c3093ef-7e94e65]
12.06 02:50:44 [Server] INFO at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527) ~[custom.jar:git-Spigot-c3093ef-7e94e65]
12.06 02:50:44 [Server] INFO at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680) ~[custom.jar:git-Spigot-c3093ef-7e94e65]
12.06 02:50:44 [Server] INFO at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484) ~[custom.jar:git-Spigot-c3093ef-7e94e65]
12.06 02:50:44 [Server] INFO at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858) ~[custom.jar:git-Spigot-c3093ef-7e94e65]
12.06 02:50:44 [Server] INFO at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079) ~[custom.jar:git-Spigot-c3093ef-7e94e65]
12.06 02:50:44 [Server] INFO at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013) ~[custom.jar:git-Spigot-c3093ef-7e94e65]
12.06 02:50:44 [Server] INFO at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104) ~[custom.jar:git-Spigot-c3093ef-7e94e65]
12.06 02:50:44 [Server] INFO at com.mysql.jdbc.PreparedStatement.executeBatchedInserts(PreparedStatement.java:1548) ~[custom.jar:git-Spigot-c3093ef-7e94e65]
12.06 02:50:44 [Server] INFO ... 11 more

**Comment by md-5** [comment]
https://github.com/LogBlock/LogBlock/wiki/FAQ
