### ISSUE TITLE
Question: toolblock placement, actually places it.

### ISSUE THREAD

**Issue by andrewkm** [LogBlock/LogBlock#719]
Just updated from 1.12.2 to 1.13.1
Running your very latest dev build as of this post.

Config looks as such:
https://pastebin.com/raw/BaZxgWe7

Back on 1.12.2 when I do /lb tb - I get an ice block, which I can left click and right click.

On the new 1.13.1 version, when I left click, all is well, but when I right click, it actually places it as opposed to telling me the information on that area and returning the ice to me.

What am I doing wrong lol?

**Comment by Brokkonaut** [comment]
I cannot reproduce this - Probably some other plugin causes that behavior.

**Comment by andrewkm** [comment]
Was a confliction with @derkades 's ServerSelector premium plugin, a bug that's now been fixed :)
