### ISSUE TITLE
How to migrate single table to 1.13 data structure?

### ISSUE THREAD

**Issue by xDeeKay** [LogBlock/LogBlock#720]
I have a single table that failed to migrate due to insufficient space while migrating all the data for the new 1.13 structure. How does one go about migrating just one table? Attempting to drop the empty "lb-world-blocks" table simply generates a new empty blocks table on startup.

**Comment by Brokkonaut** [comment]
You can set the version field in the logblock config to 1.12.0 - So it will try to continue converting the database on the next start

But please create a full database backup before. I'm not sure if that works at all, because the database could be in an unexpected state

**Comment by xDeeKay** [comment]
Thanks for that, it worked just fine.
