### ISSUE TITLE
Log stripped logs as block interact / block break.

### ISSUE THREAD

**Issue by mibby** [LogBlock/LogBlock#725]
In 1.13, players can grief by stripping logs of wood. This does not show up in LogBlock as any block break or interact event so it is unable to be rolled back. Can stripping logs be logged and rolled back as block break or a new interact option?

**Comment by Brokkonaut** [comment]
I cannot reproduce this, when I strip a log, it is logged as something like "... replaced OAK_LOG with STRIPPED_OAK_LOG". It is logged from the BlockPlace listener. And it can be rolled back.

Are you using the latest Spigot/Paper and LogBlock? And do you have blockplace enabled in the logblock worlds config?

**Comment by mibby** [comment]
Verifying and checking again personally, it seems to be fine. I can only assume perhaps the staff member who reported it was incorrectly checking the source block in front or perhaps misclicked.

My apologies!

**Comment by mibby** [comment]
Verifying and checking again personally, it seems to be fine. I can only assume perhaps the staff member who reported it was incorrectly checking the source block in front or perhaps misclicked.

My apologies!
