### ISSUE TITLE
Could not pass event EntityDeathEvent

### ISSUE THREAD

**Issue by seema84** [LogBlock/LogBlock#733]
https://pastebin.com/XpwwXGU4

latest Spigot build 1.13.2-R0.1-SNAPSHOT
LogBlock Build 384

**Comment by seema84** [comment]
i use atm the worldedit  beta 1

**Comment by seema84** [comment]
yes that's what I did

**Comment by Brokkonaut** [comment]
Should be fixed when using the latest WorldEdit builds (http://builds.enginehub.org/job/worldedit?branch=master)
