### ISSUE TITLE
wall_torch problem

### ISSUE THREAD

**Issue by seema84** [LogBlock/LogBlock#734]
old torches on the wall will ignor on rollback commands
is there any solution possible?

**Comment by Brokkonaut** [comment]
I'm not sure what exactly the problem is - Were those torches changed before updating to 1.13? Were they placed or destroyed? What is the message if you use a toolblock on the changed torch?

**Comment by seema84** [comment]
old wall torches are logged at unspecified action
that's why they're ignored in the rollback
