### ISSUE TITLE
Chestdata tables are generated even when their logging is disabled

### ISSUE THREAD

**Issue by Phoenix616** [LogBlock/LogBlock#737]
Tables for chest logging seem to be generated even when the logging of chests is turned off due to chest logging not being checked [here](https://github.com/LogBlock/LogBlock/blob/71527530f2951cac08f7f3e96952be6338a8c3e3/src/main/java/de/diddiz/LogBlock/Updater.java#L818). Not really a big issue but makes the database a bit more messy, not sure if just disabling the generation there does have some side effects in the new update though, [my modifications](https://github.com/Minebench/LogBlock/commit/f47cba2c197908e2edb0b5333b9006c9477f4aaf) seem to have worked without issues in the previous version though.

**Comment by Brokkonaut** [comment]
Many database operations (lookup, rollback, clearlog, ..) may join on that table (depending on the params), so all of them would have to be checked if the table might not exist to avoid exceptions
