### ISSUE TITLE
[ClearLog] Exception while dumping log: java.sql.SQLException: Access denied for user

### ISSUE THREAD

**Issue by masterstreamer** [LogBlock/LogBlock#741]
I already red your answer to disable logdump, but I want to save these logs. The database is hosted on the same machine using plesk. Its a Windows 2016 Server. Is there a way to enable this?

**Comment by Brokkonaut** [comment]
Access denied is something completely different - This says that the user/password for the database (in the config) is incorrect

**Comment by masterstreamer** [comment]
@Brokkonaut But writing in database and all other functions of logblock are working fine...

**Comment by Brokkonaut** [comment]
Do you have a limited the available amount of database connections in the database config?

**Comment by masterstreamer** [comment]
@Brokkonaut Nope

**Comment by Brokkonaut** [comment]
Does the sql account have DELETE permissions on the tables?

**Comment by Brokkonaut** [comment]
Do you use the latest build from here: https://www.iani.de/jenkins/job/LogBlock/ ?

**Comment by Brokkonaut** [comment]
Does this issue still occur?

**Comment by masterstreamer** [comment]
No, it is fixed. Thank you!
