### ISSUE TITLE
Logblock 1.14 ?

### ISSUE THREAD

**Issue by Blueeyestar** [LogBlock/LogBlock#749]
Will there be a 1.14 version? Because I haven't read anything about it yet. Does anyone know anything more?

**Comment by Brokkonaut** [comment]
There will be a 1.14 update. Its somewhat ready, but not completely tested.
You can try this branch: https://github.com/LogBlock/LogBlock/tree/1.14pre if you want, but please make a backup first and I would not yet recommend to use it on a production server.

**Comment by Blueeyestar** [comment]
Thank you for the link and tip.  You are doing a great job with Logblock.  You have to do this on every server that is good :)

**Comment by Brokkonaut** [comment]
1.14.1 builds are now available.
