### ISSUE TITLE
import dumped database

### ISSUE THREAD

**Issue by masterstreamer** [LogBlock/LogBlock#752]
Hi,
I just tried to move the database from a server to another. I got a export from the first one (6GB). I tried to import into the new server, it lasts long but works. After that I checked, the tables were correctly restored and the data too. 
But if I am using this database ingame, there are no logs for anything before the movement.
The log says "Creating table ....", but this table already exists!
Do I have to change anything else?

Thanks in advance!

**Comment by Brokkonaut** [comment]
Did you select the correct database in the logblock config? It will only create tables if they are not found in the selected database.

**Comment by masterstreamer** [comment]
@Brokkonaut Sure. This database is the only one which exists on that server.
