### ISSUE TITLE
1.14.1

### ISSUE THREAD

**Issue by Bobbbe** [LogBlock/LogBlock#754]
Hi Brokkonaut :)
Since 2 days I work with the 1.14 and your build # 64 and everything works very well, good job :)
today I installed 1.14.1 and your build # 65 and I have this, https://pastebin.com/U5LjZ5zY
I know it's fast, I just want to inform you since I know you're working on the update :)

Have a nice day.
Bobbber

**Comment by Brokkonaut** [comment]
Please try build 66

**Comment by Bobbbe** [comment]
You are a champion and very fast ! good job. all works very well :) thx again.
