### ISSUE TITLE
Logblock Losing Connection

### ISSUE THREAD

**Issue by Shadezc** [LogBlock/LogBlock#756]
Currently I am using LogBlock v1.13.2 (Build #64) on my minecraft server running Spigot v1.13.2. As of lately I've been receiving the following error to seemingly no end:

https://pastebin.com/JEMvJA1M

I'm no expert on deciphering errors, and I honestly am not even sure what to begin searching. To my knowledge the only build beyond this one are the ones designed for 1.14. So I am unsure of what to do to resolve this error. Any help would be appreciated. Thanks.

**Comment by Shadezc** [comment]
I closed this because I believed that the second issue under #732 was the same as mine, however upon looking closer I realized that not only does my connection get described as broken, but it also has the same line from the first issue. Where it states there was a communications link failure, similar to the first issue under the aforementioned number. So my connection is described as broken due to SQLSTATE, then a communications link failure occurs. Is this the same as the latter issue on #732 or a different one?

**Comment by Shadezc** [comment]
After sitting for about 10 minutes, it begins sending these errors about every 30 seconds.

https://pastebin.com/ZzXNpdcz

**Comment by Brokkonaut** [comment]
I don't know what exactly, but something is killing your mysql connections. If the mysql server is operated by a hosting company, you should ask them.

**Comment by Shadezc** [comment]
I asked them, and previously they tried telling me it was the plugin. Thats why I'm here. I'll reach back out to them. Thanks!
