### ISSUE TITLE
LogBlock for 1.12.2 download

### ISSUE THREAD

**Issue by s1h4d0w** [LogBlock/LogBlock#758]
I was sort of apprehensive about making an issue for this question, but I couldn't find a good way to contact the dev. I'm wondering if I can use the latest build on 1.12.2.

[Now I found this issue from 2017](https://github.com/LogBlock/LogBlock/issues/699), but looking at the Jenkins page I see "Please use build 64 for Spigot 1.13.2" at the top, which makes me think that the latest version doesn't work with earlier versions of MC.

Could someone tell me which build I need, or is build 64 specifically for just 1.13.2? Would be nice to add which MC versions LogBlock supports to the Jenkins and Github page, as the bukkig.org page just shows a "not found" error.

**Comment by Brokkonaut** [comment]
As I am the only active LogBlock dev and I do not have the time to maintain more than one version of LogBlock all old versions are mostly unsupported. 

You can use this branch https://github.com/LogBlock/LogBlock/tree/version/1.12 to build a LogBlock for 1.12.2, but I cannot offer any support for it.

**Comment by s1h4d0w** [comment]
Thank you, will try that. Hope you can find some more developers to help you, I appreciate the work.

**Comment by Brokkonaut** [comment]
It does not build that. The resulting jar should be in the target folder.

**Comment by s1h4d0w** [comment]
Got it, I'm dumb, thanks!
