### ISSUE TITLE
Errors when placing/removing books from lecterns.

### ISSUE THREAD

**Issue by selfslaughter** [LogBlock/LogBlock#761]
Logblock seems to throw an error when placing or removing a book from a Lectern using LogBlock v1.14.1-SNAPSHOT (build #76) on a paper 1.14.3 (build #125) server.

Looking at the blocks history, it still shows "xxx took 1x WRITABLE_BOOK", or "xxx took 1x WRITTEN_BOOK". Although no history on anyone actually placing the books.

https://pastie.io/eihayw.sql

**Comment by Brokkonaut** [comment]
Looks like Spigot broke something there.  I will try to fix it when I have time for it.

**Comment by Brokkonaut** [comment]
Should be fixed
