### ISSUE TITLE
Failure to register the beacon

### ISSUE THREAD

**Issue by Mundo-Minecraft** [LogBlock/LogBlock#762]
I have the latest version of logblock (# 77) and the last version of spigot. And a bug happens with the beacon, when I place it, logblock registers that it has been placed. But breaking it does not register it.

Greetings and thanks.

PD: in the server log does not indicate failure

**Comment by Brokkonaut** [comment]
I cannot reproduce this. Did you test it without any other plugins (plugins might override the break action)? do you have "BLOCKBREAK: true" in the logblock config for that world?

**Comment by Mundo-Minecraft** [comment]
It is strange, any other block is registered correctly. It only happens with the beacon.

Example: https://www.youtube.com/watch?v=bzt6cwtkRoA&feature=youtu.be

can it be some plugin that affects the logblock? It is rare that some plugin only affects the beacon, right?

greetings and thanks

**Comment by Brokkonaut** [comment]
Yes, plugins can affect the logging. Every block break sends an event - if a plugin changes the breaking behavior of some block it can cancel that event, so nothing will be logged.

On my test servers without plugins and with some widely used plugins beacon breaking is logged, so I think it has to be one of the plugins on your server.

**Comment by paul-maxime** [comment]
We have the same problem on our server. No plugin changing anything about broken blocks or the beacon material.

**Comment by Brokkonaut** [comment]
Thanks
