### ISSUE TITLE
not logging chests

### ISSUE THREAD

**Issue by Spryc** [LogBlock/LogBlock#770]
I have enabled chest access but i just open the chest when i right click with the tool. It works for barrels tho

**Comment by Brokkonaut** [comment]
Is there any error in the console? What is your plugin version and configuration?

**Comment by Brokkonaut** [comment]
Can you post the full stack trace of the exception?

**Comment by Spryc** [comment]
https://pastebin.com/vHWHZdwv

Den tis 17 sep. 2019 02:15Brokkonaut <notifications@github.com> skrev:

**Comment by Brokkonaut** [comment]
Can you please try the dev builds from here: https://www.iani.de/jenkins/job/LogBlock/ Afaik that bug is already fixed in those dev builds.

**Comment by Cr1mSoN0** [comment]
not work

**Comment by Cr1mSoN0** [comment]
barrels and chests
