### ISSUE TITLE
 Error with mobhunting

### ISSUE THREAD

**Issue by Mundo-Minecraft** [LogBlock/LogBlock#773]
Hello, on my server I use the plugin https://www.spigotmc.org/resources/mobhunting.3582/ until recently everything was fine, but a few days ago the moderators have realized that logblock does not register the plugin heads well . Record when placed but not when it breaks. It reminds me of what I report on the beacons https://github.com/LogBlock/LogBlock/issues/762

Video attachment: https://www.youtube.com/watch?v=gtjdxo58aOo&feature=youtu.be

PD: the server is in the latest compilation of spigot, logblock and mobhunting.

Regards.

**Comment by Mundo-Minecraft** [comment]
I provide the report I sent to the creator of MobHunting.

https://github.com/Rocologo/MobHunting/issues/577

Thanks and regards.

**Comment by Brokkonaut** [comment]
I don't think that it is fixable from the LogBlock side. MobHunting removes the block before the event reaches LogBlock. https://github.com/Rocologo/MobHunting/blob/master/src/one/lindegaard/MobHunting/rewards/RewardManager.java#L600

The only possible fix would be a custom LogBlock entry that MobHunting could create.
