### ISSUE TITLE
Rollback agressiv mobs

### ISSUE THREAD

**Issue by kf-jerryh** [LogBlock/LogBlock#778]
Hello,
I'm a moderator of a french minecraft server and I want to know if it will possible to rollback agressiv mobs which might be useful in farms like withers.

Thank you for reading this issue and sorry for my bad english.

**Comment by TheMolkaPL** [comment]
Have you tried `entities` parameter?

**Comment by SuperMighty0** [comment]
I tried entities as arg but it only rollback passiv mobs

**Comment by Brokkonaut** [comment]
In the default configuration not all mobs are logged. have a look at the file LogBlock/world.yml (or the name of the world). In the entity section you can add "ALL" or "WITHER" to the destroy subsection, so they will be logged when they are killed.

**Comment by SuperMighty0** [comment]
I will ask for it to my administrator, thank you very much, I will answer you when it will be done
