### ISSUE TITLE
Error on startup, with suggested resolution: "Could not connect to the Database! Please check your config! Failed to get driver instance for jdbcUrl=jdbc:mysql://localhost:3306/logblock"

### ISSUE THREAD

**Issue by totemo** [LogBlock/LogBlock#784]
The above error happens when LogBlock is getting its initial connection. It results in the plugin being disabled.

I get this under very specific conditions with the latest LogBlock snapshot:
```
[LogBlock] Enabling LogBlock v1.15.1.1-SNAPSHOT (build #96)
[LogBlock] Connecting to minecraft@jdbc:mysql://localhost:3306/logblock...
[de.diddiz.lib.com.zaxxer.hikari.HikariDataSource] LogBlock-Connection-Pool - Starting...
[LogBlock] Could not connect to the Database! Please check your config! Failed to get driver instance for jdbcUrl=jdbc:mysql://localhost:3306/logblock
```

 * I'm on Fedora 30 Linux 5.4.17-100.fc30.x86_64
 * Java 11: java-11-openjdk.x86_64 (/usr/lib/jvm/java-11-openjdk-11.0.6.10-0.fc30.x86_64/bin/java)
 * Latest (or thereabouts) Paper build: git-Paper-102 (MC: 1.15.2)
 * MariaDB (MySQL) version: Ver 15.1 Distrib 10.3.21-MariaDB, for Linux (x86_64) using readline 5.1
 * This version of LogBlock works fine in PaperSpigot for 1.14.4 on Fedora with the same Java and also works fine on Ubuntu with mysql Ver 14.14 Distrib 5.5.62, for debian-linux-gnu (x86_64) using readline 6.3 paired with Java 11 and the same 1.15.2 PaperSpigot.
 * I'm a bit worried that this issue might bite me with LogBlock in production on a later version of Ubuntu with a later mysql.

 * I tried rebuilding LogBlock myself with the HikariCP dependency updated to 3.4.2. That didn't help.
 * I drew on the suggested resolution in [this StackOverflow answer](https://stackoverflow.com/a/19259608) to call `Class.forName("com.mysql.jdbc.Driver");` (note that calling `DriverManager.registerDriver()` is strongly discouraged). Bada bing badaboom that works with either HikariCP 3.4.1 or 3.4.2.
 * I just stuck it in `getConnection()` per the patch below, but that may not be the best place for it. However this is an issue that does need to be resolved somehow, since LogBlock is disabled otherwise.

```
diff --git a/src/main/java/de/diddiz/LogBlock/LogBlock.java b/src/main/java/de/diddiz/LogBlock/LogBlock.java
index 613162b..9c54e8d 100644
--- a/src/main/java/de/diddiz/LogBlock/LogBlock.java
+++ b/src/main/java/de/diddiz/LogBlock/LogBlock.java
@@ -251,6 +251,7 @@ public class LogBlock extends JavaPlugin {
 
     public Connection getConnection(boolean testConnection) {
         try {
+            Class.forName("com.mysql.jdbc.Driver");^M
             final Connection conn = pool.getConnection();
             if (!connected) {
                 getLogger().info("MySQL connection rebuild");
```

Please and thank you.

**Comment by Brokkonaut** [comment]
should be fixed now

**Comment by totemo** [comment]
Confirmed good on the build 99. Thanks.
