### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by iTaeyeonKim** [LogBlock/LogBlock#785]
Server version: 1.14.4
LogBlock: 1.15.2

Last few days, I constantly getting this error in console:

https://pastebin.com/SHrymGmx

**Comment by Brokkonaut** [comment]
The latest logblock builds are for minecraft 1.15(.2) only. For a 1.14.4 server you can use this (older) build: https://www.iani.de/jenkins/job/LogBlock/90/
