### ISSUE TITLE
How to prevent using logblock on chests that are not yours (LWC)?

### ISSUE THREAD

**Issue by andrewkm** [LogBlock/LogBlock#786]
How do you prevent using logblock on chests that are not yours (LWC)?
From what I remember this used to be a thing, but for some reason it's not anymore.

Any ideas?
Has logblock always worked on chests that aren't your's when it comes to LWC or is there a new setting/permission somewhere that I'm missing?

**Comment by Brokkonaut** [comment]
Logblock never had any LWC integration, so it cannot check if a chest is LWC protected or not.

But there is a BlockChangePreLogEvent called by LogBlock - this could be used by another plugin to check if a change should be logged or not.

**Comment by andrewkm** [comment]
Ok thanks :)
