### ISSUE TITLE
Entities are not logging

### ISSUE THREAD

**Issue by Vejksu42** [LogBlock/LogBlock#793]
When i tried to rollback killed entities (cow, sheep) using **/lb rollback entities**, i got a message "0 entities found."

config.yml: https://pastebin.com/BW0xcx9u
world.yml: https://pastebin.com/KTzRHBxb

Build 99
Paper-146 1.15.2

**Comment by Brokkonaut** [comment]
Do you have log entries in "/lb entities coords" (or something similar)?

**Comment by Vejksu42** [comment]
> 
> 
> Do you have log entries in "/lb entities coords" (or something similar)?

No, I do not have it.

**Comment by Vejksu42** [comment]
I solved my problem. WorldEdit should have been installed.
