### ISSUE TITLE
Text for Warped and Crimson Signs / Wall Signs not getting logged

### ISSUE THREAD

**Issue by josephrooks** [LogBlock/LogBlock#795]
What's expected: Sign text logging similar to what currently works for all overworld sign type text.

What is happening: Lookup is giving "username edited a WARPED_WALL_SIGN to" and then blank after that.

**Comment by Brokkonaut** [comment]
Oh, I think I forgot to add the new signs. Please try the latest build from https://www.iani.de/jenkins/job/LogBlock/ it should be fixed now

**Comment by josephrooks** [comment]
Thanks! I will test it and report back, probably tomorrow sometime.

**Comment by josephrooks** [comment]
Finally got around to testing and this seems to work just fine now. Thanks!
