### ISSUE TITLE
Question kill weapon

### ISSUE THREAD

**Issue by vacla** [LogBlock/LogBlock#797]
As I read the code it should say with which weapon something got killed, but I can't get that for some reason. We tried with coords and normal command to get kill logs but nothing, any idea how to get it?

**Comment by Brokkonaut** [comment]
Can you please post the commands you used? The used weapon is only available for /lb kills, not for the new /lb entities

**Comment by vacla** [comment]
I was using /lb entities and apparently /lb kills was blocked on the server when i was testing, ty for answering, I needed the info for my mod "Watson" to get info from LogBlock.
