### ISSUE TITLE
Mysql purge

### ISSUE THREAD

**Issue by Volgeop** [LogBlock/LogBlock#798]
Hi, is it possible to purge mysql entries? I asked already in thread discussion, maybe reply me there please. If not, could you add it please?

**Comment by Brokkonaut** [comment]
Yes, you can use "/lb clearlog <params>" to delete unneeded log entries. For example "/lb clearlog before 30d" would delete all logs that are older than 30 days (you can automate clearlog in the logblock config). You can use most params that can be used in querys.

Another option is to manually remove entries from the database. Deleteing from lb-worldname-block and lb-worldname-entities is safe, lb-worldname-state, lb-worldname-chestdata and lb-worldname-entityids have referenced entries, so only delete those that are no longer in use.

entries from other tables (lb-players, lb-materials, lb-blockstates, lb-entitytypes) should never be removed.

**Comment by Volgeop** [comment]
Ok, thanks :D
