### ISSUE TITLE
The newest WE support?

### ISSUE THREAD

**Issue by Volgeop** [LogBlock/LogBlock#802]
Hi, could you add the newest WE support please?
[16:29:59] [Server thread/ERROR]: [LogBlock] No compatible WorldEdit found, entity logging will not work!

WorldEdit version 7.2.0-beta-03+94ce464

**Comment by paul-maxime** [comment]
Hi, the latest WorldEdit build works fine for me (build 5298, commit 232ced8):

https://builds.enginehub.org/job/worldedit/15665
`worldedit-bukkit-7.2.0-SNAPSHOT-dist.jar`

**Comment by Volgeop** [comment]
And you don't have this message in log?

**Comment by paul-maxime** [comment]
No, you are probably using an older version of WorldEdit.

You should try this one:
https://builds.enginehub.org/job/worldedit/15665 (the most recent one)

Or this one:
https://dev.bukkit.org/projects/worldedit/files/3039216 (the latest stable)

**Comment by Volgeop** [comment]
[04:13:44] [Server thread/INFO]: [LogBlock] [Updater] Current Minecraft Version: '1.16.3'
[04:13:44] [Server thread/ERROR]: [LogBlock] No compatible WorldEdit found, entity logging will not work!

Using this and happening again. @Brokkonaut

**Comment by paul-maxime** [comment]
The WorldEdit version you use is compatible with 1.16.2, not 1.16.3.

You can download the latest WorldEdit builds here:
https://builds.enginehub.org/job/worldedit?branch=master
