### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Volgeop** [LogBlock/LogBlock#805]
Hi, my two server crashes and there's Logblock mentioned at the start, don't you know what was wrong please or how to solve it?
https://pastebin.com/akz6uRPX
https://pastebin.com/akz6uRPX

**Comment by Brokkonaut** [comment]
It looks like you had issues with your database - Many stracktraces in that log contain com.mysql.jdbc.MysqlIO. The crash stacktrace is in lines 639 to 673, the plugin mentioned there is org.mineacademy.chatcontrol. But I don't think that this plugin is the cause of the server crash, but a not responding mysql server.

**Comment by Volgeop** [comment]
And don't you know why my db didn't respond? Any ideas, what can be done to preveent it?

**Comment by Brokkonaut** [comment]
No, I don't know, there could be various causes for that..
