### ISSUE TITLE
Not working with LuckPerms

### ISSUE THREAD

**Issue by KleinCrafter** [LogBlock/LogBlock#806]
I use LogBlock and LuckPerms
After Updating LuckPerms to Version 5.2.31 LogBlock stop Working...
https://bytebin.lucko.me/AVCpTGXSI7

I add a line of Code to `de.diddiz.util.MySQLConnectionPool`
`ds.addDataSourceProperty("serverTimezone", "UTC");`

Works fine... not .. now LookUp is broken: https://bytebin.lucko.me/OiArLr4wPQ

I downgrade to LuckPerms Version 5.2.28 and it works fine. (Last working Version, 5.2.29 don't work)
Hope it wil help others...

**Comment by lucko** [comment]
My apologies, this was a LuckPerms error.

https://github.com/lucko/LuckPerms/commit/9af6dccd9dc2fd5d878dfffc36caae8edcfa51d8

Please try again using `v5.2.33` or newer of LP. (https://luckperms.net/download)

**Comment by KleinCrafter** [comment]
The Update `v5.2.34` work fine with the latest LogBlock Version.
