### ISSUE TITLE
Failed to validate connection

### ISSUE THREAD

**Issue by seema84** [LogBlock/LogBlock#808]
This server is running Paper version git-Paper-253 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
Loading LogBlock v1.16.1.2-SNAPSHOT (build #459)

I get this warning after a reboot and the first player join

[14:01:10] [User Authenticator #1/INFO]: UUID of player Player is 42ad3a-33f0-46b3-adf8-8bdd583551a3
[14:01:10] [Logblock-Consumer/WARN]: [de.diddiz.lib.com.zaxxer.hikari.pool.PoolBase] LogBlock-Connection-Pool - Failed to validate connection com.mysql.jdbc.JDBC4Connection@236ce8b4 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[14:01:10] [Logblock-Consumer/WARN]: [de.diddiz.lib.com.zaxxer.hikari.pool.PoolBase] LogBlock-Connection-Pool - Failed to validate connection com.mysql.jdbc.JDBC4Connection@729b46f5 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.

**Comment by Brokkonaut** [comment]
This is no issue. It just says mysql has closed the logblock database connection (mostly because of a session timeout) and logblock will create a new connection.

You could increase the max idle time for connections in the mysql server or just ignore the message. https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_wait_timeout

**Comment by seema84** [comment]
okay thanks @Brokkonaut

**Comment by seema84** [comment]
what value needs wait_timeout to avoid this warning?

**Comment by Brokkonaut** [comment]
The default (28800) should be fine

**Comment by seema84** [comment]
i use the default value (28800) and receive this warning

MariaDB [(none)]> SHOW SESSION VARIABLES LIKE 'wait_timeout';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| wait_timeout  | 28800 |
+---------------+-------+
1 row in set (0.007 sec)

**Comment by Brokkonaut** [comment]
Maybe something else is closing the connections? I don't know

**Comment by seema84** [comment]
its maybe a HikariCP problem?
i have read that maxLifetime must be < wait_timeout (mysql)

**Comment by Brokkonaut** [comment]
yes, maybe

**Comment by Brokkonaut** [comment]
default max lifetime is 30 minutes in hikari and it is not changed in logblock, so this should not cause the issue.

**Comment by seema84** [comment]
is this relevant for this issue?

https://www.spigotmc.org/threads/mysql-no-operations-allowed-after-connection-closed.400400/#post-3582010

**Comment by Brokkonaut** [comment]
No, the mysql connections for logblock are handled by the HikariCP.

**Comment by seema84** [comment]
https://github.com/brettwooldridge/HikariCP/issues/1328#issuecomment-731596234

**Comment by seema84** [comment]
Hey @Brokkonaut,
it was really the wrong "wait_timeout" value. The session value was correct but global was a different value.

Thanks for your help!
