### ISSUE TITLE
Corrupted logs causing client kick

### ISSUE THREAD

**Issue by CalleyInc** [LogBlock/LogBlock#809]
Hi, I recently got a griefer on my server. He's exploded some terrain, trying to check logs with /lb rb or /lb lookup causes kick with reason that client unable to decode server json reply

From console although there some logs accessible, but I unable to rollback it
![2020-11-28_22 01 59](https://user-images.githubusercontent.com/43775511/100526049-8d668280-31d6-11eb-965e-3616a219b18c.png)

**Comment by Brokkonaut** [comment]
Its not a logblock bug, but this one: https://hub.spigotmc.org/jira/browse/SPIGOT-6056

I do not know if there is some other plugin that modifies the messages incorrectly or if its a spigot/bungee bug. But there is nothing I could do in logblock to prevent it. logblock only creates valid messages using the component api: https://github.com/LogBlock/LogBlock/blob/master/src/main/java/de/diddiz/util/MessagingUtil.java#L44
