### ISSUE TITLE
Players can obtain and place bedrock blocks

### ISSUE THREAD

**Issue by ULTUX** [LogBlock/LogBlock#811]
One of my friends recently found a bug that allows them to place bedrock using /lb toolblock command.

## How to reproduce:
1. use /lb toolblock command
2. place bedrock to offhand
3. use command /lb toolblock off
4. You've just obtained placable bedrock block.

**Comment by Brokkonaut** [comment]
There are many more ways to get any amount of tool items (for example putting the tool into a chest or die while having it in the inventory), so i would not give the logblock.spawnTools permission to any untrusted user. If you want untrusted users to use a toolblock better use some item they can obtain as tool item and do not give them the logblock.spawnTools permission
