### ISSUE TITLE
Cannot disable chat logging (false don't work in config)

### ISSUE THREAD

**Issue by Chevels** [LogBlock/LogBlock#813]
Hello there :)

Since monthes I have a problem with the "chat" table in my database: it fills up while the chat log is disabled in all my worlds.
So I have to empty it by hand regularly because it can reach several GB.
I have been using Logblock since 2011 and have never had this problem in previous years. I haven't changed anything in my config, yet Logblock decided on its own to log the chat and I don't understand why.

Is this a bug ? How can I fix this ?

**Comment by Brokkonaut** [comment]
Is it really chat or commands in the logs? if its commands, you have to set `PLAYER_COMMANDS: false` in the worlds configs, otherwise it should be `CHAT: false`.

**Comment by Chevels** [comment]
Hi,
sorry I was away for 15 days and I only came back last night. So the problem came from the option:
COMMANDBLOCK_COMMANDS: true
My server being a roleplay server with a lot of command blocks (quests, dungeons ...) the command block log used 8GB in my database in just a few weeks.
Since I set the option to "false" everything seems to be fine. Thank you for helping !
