### ISSUE TITLE
[BUG/ERROR] QueryParams | StringIndexOutOfBoundsException: String index out of range: -2

### ISSUE THREAD

**Issue by Voyaris** [LogBlock/LogBlock#814]
Hey
I was playing a bit with the API and uncovered a bug.
Location: [QueryParams.java](https://github.com/LogBlock/LogBlock/blob/master/src/main/java/de/diddiz/LogBlock/QueryParams.java#L232)

LogBlock-Version: v1.16.1.2-SNAPSHOT
Paper-Version: git-Paper-439 (MC: 1.16.5)

Error-message
![image](https://user-images.githubusercontent.com/25487038/105756460-f35c5580-5f4c-11eb-84db-8b748b608a59.png)

My code
![image](https://user-images.githubusercontent.com/25487038/105756714-42a28600-5f4d-11eb-91e7-7417a317c51b.png)

**Comment by Brokkonaut** [comment]
You have to set at least one of the need* fields of the QueryParams to true. Otherwise there is nothing to select and the query does not work.

See here for an example: https://github.com/LogBlock/LogBlock/blob/master/src/main/java/de/diddiz/LogBlock/CommandsHandler.java#L494-L512

**Comment by Voyaris** [comment]
Okay got it!
But what do I have to set so that I can query the following:
I have an org.bukkit.block and want to query this has already mined.
If not / it was not mined by a particular player -> chat message
