### ISSUE TITLE
Chest

### ISSUE THREAD

**Issue by Janek164** [LogBlock/LogBlock#817]
LOGBLOCK does not register items that have been removed from the chest.

**Comment by Magnum97** [comment]
It was noted in #774 that chest access logs have been broken for some time.  I would love to see this feature restored as well. I've been going out of my mind trying to figure out what I did wrong until I came here to find this, so thank you for saving my sanity ^_^

**Comment by Brokkonaut** [comment]
Yes it would be great to have this fixed. Sadly currently I do not have the time to do it, but PRs are very welcome.

Here is some initial work someone did: https://github.com/sijmn/LogBlock/commit/c1517b2e9e7cbb4e00d84a787b8e6120fbc24a6e

**Comment by Magnum97** [comment]
Fantastic! I will have a look at that- thank you.
