### ISSUE TITLE
YAMLException: invalid string value has occurred

### ISSUE THREAD

**Issue by andrewkm** [LogBlock/LogBlock#820]
Could not pass event BlockPlaceEvent to LogBlock
**BlockPlace** https://pastebin.com/u4aPSsU6
**BlockBreak** https://pastebin.com/raw/vvAX7sNu

**Paper** 1.16.5 Build 488
**Logblock** Build 468 from md_5 jenkins.

**Comment by Brokkonaut** [comment]
This looks like some of the blocks/items on your server have an invalid string (that is not expressible as utf-8) in the name, lore or book content.

See here, where the exception is thrown:
https://github.com/asomov/snakeyaml/blob/4ff91587d4e3907d9f54a6854da5b933496fde39/src/main/java/org/yaml/snakeyaml/representer/SafeRepresenter.java#L126-L134

There is not much, that I could do to fix this in logblock. The best way to avoid errors like this is to filter the strings when they are set.

**Comment by nicolube** [comment]
Here happens the same...
Also happened to "angelchest free".
but they have made an update that fixed that...

**Comment by Brokkonaut** [comment]
> Happens to me on every lookup exept unchanged blocks

Can you please post a stack trace to see if its the same issue? (Because that should only be able to happen on creating entries like break/place and not on lookups)

**Comment by nicolube** [comment]
It doesn't make one...

Not in the client log and not in the server log...

U just get this message in the screen then u get disconnected from the server...

**Comment by nicolube** [comment]
Ohh sorry miss read the exaeption...

**Comment by nicolube** [comment]
I got an error with the client decoding of an message component

**Comment by Brokkonaut** [comment]
@nicolube It might be this issue: https://github.com/LogBlock/LogBlock/issues/809. This is not caused by logblock but by other plugins that incorrectly shade spigot components.
