### ISSUE TITLE
Operation not allowed for a result set exception with MariaDB database

### ISSUE THREAD

**Issue by Bloodlex** [LogBlock/LogBlock#821]
I have such issue when executing any LogBlock command:

[https://pastebin.com/adcyWDUV](https://pastebin.com/adcyWDUV)

I have MariaDB database. Here is my config file:

[https://pastebin.com/CjCJ9P9Z](https://pastebin.com/CjCJ9P9Z)

If I copy this SQL query and execute it on the database it works fine (the same query). I don't know where the problem lies.

It used to work fine until today. I don't know why it stopped 😢 Please help 😢 

Thank you very much. It's a great plugin and I really need that on my server.

**Comment by Bloodlex** [comment]
@Brokkonaut Could you please help with that? 😢

**Comment by Brokkonaut** [comment]
It looks like some other plugin you use accidentally replaced the mysql connector and that breaks logblock. Can you have a look what plugin uses the package names starting with plan.com (in the plugin's jar opened with some zip file editor like 7zip there should be the directory plan/com/mysql) that plugin has to be fixed to allow making logblock the connections.

if you don't know how to find it just look for plugin you recently updated/added and try to remove or downgrade them.

**Comment by Bloodlex** [comment]
@Brokkonaut Yes! You are right. It is **[Plan | Player Analytics](https://www.spigotmc.org/resources/plan-player-analytics.32536)** plugin in the newest version, which I've updated recently on. THANK YOU SO MUCH 👍 I've restored the previous version of that and it works.

**Comment by C4K3** [comment]
This seems to be an issue in latest paper, probably caused by this commit https://github.com/PaperMC/Paper/commit/d560151ecdad2eabccda797883c9e699b0985104

**Comment by Brokkonaut** [comment]
> This seems to be an issue in latest paper, probably caused by this commit [PaperMC/Paper@d560151](https://github.com/PaperMC/Paper/commit/d560151ecdad2eabccda797883c9e699b0985104)

Yes paper did something similar to what player analytics did in that commit by replacing the mysql connector. Latest paper should work with that version.
