### ISSUE TITLE
Not creating mysql tables on fresh install

### ISSUE THREAD

**Issue by wrecktify** [LogBlock/LogBlock#822]
Trying to setup a fresh 1.16.5 install and am getting this error on startup.  My other plugins are able to create the needed mysql tables.  Not sure why it won't create the needed tables.

https://pastebin.com/1UcMpkvG

**Comment by selfslaughter** [comment]
In the meantime, try a slightly older version of paper (587 or earlier).
build 588 changed sql and broke a few plugins (this and lwcx for example).

**Comment by Brokkonaut** [comment]
Yes, it looks like this broke it: https://github.com/PaperMC/Paper/pull/5474 I will try to fix it when I have time for it, but for now please use Paper builds before 588

**Comment by Brokkonaut** [comment]
I did a short test and logblock could create the tables without issues using the latest paper build and the latest logblock build.

@wrecktify do you use the latest dev build of logblock ( https://www.iani.de/jenkins/job/LogBlock/ )? I looks like you use an older build. When you have updated and still have this issue please paste the new exception.

**Comment by wrecktify** [comment]
I am using Paper 591.  Updated to logblock latest version.  Still doesn't create tables.

Rolled paper back to 587.  Server started correctly and logblock made the required tables.

**Comment by Brokkonaut** [comment]
I just pushed an update, can you please try the new logblock dev build?

**Comment by wrecktify** [comment]
Tables created successfully with new dev build + paper 591

**Comment by Brokkonaut** [comment]
Ok, thank you for reporting this issue :)
