### ISSUE TITLE
LogBlock MySQL Exception (Error): "Operation not allowed for a result set of type ResultSet.TYPE_FORWARD_ONLY"

### ISSUE THREAD

**Issue by doppelkool** [LogBlock/LogBlock#825]
## Replication
Setted logblock up -> connected it with mysql -> restarted then joined on the server -> changed a block (destroyed and placed) -> checked status via logblock and got this exception:

## Error-Messages
InGame-Chat: "Block changes in the last 86400 minutes at 25:76:-76 in world: Exception, check error log"
Console: https://pastebin.com/KbkUXtqg

## Explanation
I know it's not an exception from especially LogBlock, but i was not able to find any error-fixes on the internet.

**Comment by Brokkonaut** [comment]
Please update logblock. I think that issue was fixed some time ago.

**Comment by doppelkool** [comment]
Such an easy way to fix it. I was absolutely sure that i have updated the plugin to the latest, but obv. i had not.
Thx xd
