### ISSUE TITLE
pages dont work

### ISSUE THREAD

**Issue by Philippoius** [LogBlock/LogBlock#829]
the command /lb page <number> can only be executed with the number 1. This means that you cannot call up several pages.

**Comment by Brokkonaut** [comment]
Can you please tell me your logblock and server version and what command you used to get the logs?

**Comment by Philippoius** [comment]
Serverversion: Paper version git-Paper-759 (MC: 1.16.5)
LogBlock Version: 1.16.5.1

Reproducing the error:
Place and break blocks (or use a chest, ...) at a position.
Use the lb tool to get the list of block interactions
Type "/lb page 2" or "/lb next"
Message: "There isn't a page '2'"

**Comment by Brokkonaut** [comment]
The tool will in the default settings not cache the results, so you cannot access the other pages. If you want to change that, remove the "nocache" option in the tools config.

**Comment by Philippoius** [comment]
In the config.yml section tools.tool.params we have "area 0 all sum none limit 15 desc since 180d silent"
In the whole config there is no "nocache" option set

**Comment by Philippoius** [comment]
did i miss anything or is everything correct in the config file?

**Comment by Brokkonaut** [comment]
Sorry for the late answer, I did not have much free time.

I still could not reproduce the issue, when I try your tool config, i get up to 10 results on the first page and up to 5 results on the second page ("limit 15" limits the total results to 15 so this is correct)

Did you set the lines per page "lookup.linesPerPage" in the config to 15 or more? that would explain that you never have more than one page with a max of 15 result lines.

"lookup.linesLimit" and "lookup.hardLinesLimit" in the config could also limit the results, both values should be somewhat large, 1500 and 100000 are the defaults afaik.

I would recommend to change the "limit 15" in the tool config to something higher like 150 or remove it.

**Comment by Philippoius** [comment]
Removing "limit 15" worked for me. Thanks.
