### ISSUE TITLE
Ender_crystal destroying

### ISSUE THREAD

**Issue by x1p** [LogBlock/LogBlock#830]
Situation:
Players tries to spawn the ender dragon using 4 Ender_Crystals.
A griever comes by and punches one of the end crystals.
The dragon won't spawn and the player needs another crystal.
The question is: who broke the crystal?

Question:
How can I log who destroyed the end crystal itself?
I'm not interested in the explosion or the surrounding blocks.

Solutions I tried:
End crystals are entities, so I tried adding to the `entity` section:
```yaml
entity:
  destroy:
  - ENDER_CRYSTAL
 ```
 I tried looking for signs by looking for blocks and entities. So far without result.
 What can I do to log the breaking of end crystals itself?

**Comment by Brokkonaut** [comment]
Yes, end crystals are somewhat special. The are now logged in the latest dev build
