### ISSUE TITLE
Message Component can't be decoded with client

### ISSUE THREAD

**Issue by nicolube** [LogBlock/LogBlock#832]
Hello there,

When make an lb lookup i get disconected (Conection lost) from ther server with an.

`Internal Exaption: io.netty.hander.cpdec.DecoderExeption: com.google.gson.JsonParseExeption: Don't know how to turn ... into an message Component`

Sorry I can't put there the hole thing because it does not get logged to the clent log nor server log...
It only gets displayed in the disconect window.

I knew that _AngelChest Free_ hat the same issue some time ago...

**Comment by Brokkonaut** [comment]
Probably #809. This is not caused by logblock but by other plugins that incorrectly shade spigot components or (maybe?) a spigot bug (see the linked discussion there).

You could try to remove other plugins until it works to see what plugin is causing it.
