### ISSUE TITLE
Microsoft SQL

### ISSUE THREAD

**Issue by mrtajniak** [LogBlock/LogBlock#842]
Can I use it with my Microsoft SQL database?

**Comment by Brokkonaut** [comment]
No, currently not, only MariaDB/Mysql is supported. If someone wants to add support for other DBs.. A PR would be welcome :)

**Comment by notepass** [comment]
Adding support for other DBs sounds like quite a fun challange. If nobody has volunteered I might give it a shot, if interested. Altought I certanly wouldn't be the fastest in implementing it, as I have some stuff running on the side (but I think time isn't of the essance here, so I can be a bit more leaned back with progress)
