### ISSUE TITLE
Log Block 1.18.1 does not work

### ISSUE THREAD

**Issue by GroGaloraGran** [LogBlock/LogBlock#845]
Hello
on 1.18.1 (paper 1.18.1 # 73) the plugin does not start
error from logs:
https://gist.github.com/GroGaloraGran/55adf8d1ef3ed83d32ec6a61d1424692

**Comment by Brokkonaut** [comment]
Please try the latest dev build from here: https://www.iani.de/jenkins/job/LogBlock/

**Comment by GroGaloraGran** [comment]
thank you. This version is Ok
