### ISSUE TITLE
Logblock don't follow chest activity

### ISSUE THREAD

**Issue by suhhar** [LogBlock/LogBlock#847]
I have logblock on my serwer.
The problem is: when something is put into chest or taken from it, it doesn't log it.
It only shows that chest was created or destoryed. I set the chestaccess in config file. I'm still learning all of this things and can't find the solution to my problem.

**Comment by MegaMinecraft** [comment]
Have you set the `CHESTACCESS: true` in your <world>.yml?

**Comment by suhhar** [comment]
Yes
