### ISSUE TITLE
LogBlock doesn't compile

### ISSUE THREAD

**Issue by qwertyuioplkjhgfd** [LogBlock/LogBlock#848]
When trying to compile the plugin, I get the following error indicating that the worldedit dependency is outdated:
```
[ERROR] Failed to execute goal on project logblock: Could not resolve dependencies for project de.diddiz:logblock:jar:1.17.0.0-SNAPSHOT: The following artifacts could not be resolved: com.sk89q.worldedit.worldedit-libs:core:jar:7.2.7-SNAPSHOT, com.sk89q.worldedit.worldedit-libs:bukkit:jar:7.2.7-SNAPSHOT, com.sk89q.worldguard:worldguard-bukkit:jar:7.0.6-SNAPSHOT: Failure to find com.sk89q.worldedit.worldedit-libs:core:jar:7.2.7-SNAPSHOT in https://hub.spigotmc.org/nexus/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of spigot-repo has elapsed or updates are forced -> [Help 1]
```

**Comment by Brokkonaut** [comment]
I don't know why you have that error, those files exist in the repo:

https://maven.enginehub.org/repo/com/sk89q/worldedit/worldedit-libs/core/7.2.7-SNAPSHOT/
https://maven.enginehub.org/repo/com/sk89q/worldedit/worldedit-libs/bukkit/7.2.7-SNAPSHOT/
https://maven.enginehub.org/repo/com/sk89q/worldguard/worldguard-bukkit/7.0.6-SNAPSHOT/

**Comment by qwertyuioplkjhgfd** [comment]
The problem is that worldedit declares paperlib (and other modules) as a dependency, so Maven adds it as a dependency for this project. However, we do not declare the repositories that hold paperlib so it fails to find it. Since we don't need it, we can just exclude those dependencies as per #850
