### ISSUE TITLE
unspecified action

### ISSUE THREAD

**Issue by seema84** [LogBlock/LogBlock#852]
![lb23](https://user-images.githubusercontent.com/2832339/148987385-e8634c0b-5b6e-4418-9e53-49c3a65dd0fa.PNG)

Version: LogBlock v1.17.0.0-SNAPSHOT (build 149)
Paper: Paper-408 (MC: 1.17.1)

Why is there this unspecified action? I have never seen this before.

**Comment by Brokkonaut** [comment]
It should only be there if the replaced block and the new block is "air". I currently don't know where it could come from. Maybe some incorrect conversion since the logs are from 2018?

**Comment by seema84** [comment]
_Maybe some incorrect conversion since the logs are from 2018?_

There were no major errors in the conversion, as far as I remember.

Except for the current problem and the torches (#734), I haven't noticed anything.
The problem with the torches still exists.

**Comment by seema84** [comment]
![2341](https://user-images.githubusercontent.com/2832339/149391686-e097ece8-251a-4408-814f-c87b75c606b8.PNG)

It is indeed the Air type (which was a wall_torch at the time).

**Comment by Brokkonaut** [comment]
I don't think that this is fixable any more, because it only happened with the conversion from Minecraft 1.12 to Minecraft 1.13.

If you have a backup of the unconverted data (before 1.13) it would be possible to write a script to fix those rows, but I don't think its worth the work.

**Comment by seema84** [comment]
I would probably find a backup. 
But presumably you can't just replace these air type entries with wall_torch? 
There could be other entries as well.
