### ISSUE TITLE
MySQL support broken on paper 1.19.4

### ISSUE THREAD

**Issue by selfslaughter** [LogBlock/LogBlock#866]
Same issue as coreprotect: https://github.com/PlayPro/CoreProtect/issues/352

It can connect to the database, and see the old entries, but refuses to add new entries.
I tried creating a new database to test and it would successfully connect and create the initial tables, but was unable to populate them with anything.

Tested on latest dev build (178), and 1.19 release build we were running before the switch to 1.19.4

**Comment by Brokkonaut** [comment]
I cannot reproduce this. For me it is working with Paper 1.19.4. Can you give more information? Server log, plugins, logblock configuration? (don't forget to remove passwords and other private information before uploading the config file)

**Comment by Brokkonaut** [comment]
Yes indeed they updated the bundled mysql connectors from 8.0.29 to 8.0.32 in spigot/paper. But I don't know if there were changes that could break anything.

Do you have any log messages like "[LogBlock] [Consumer] Could not connect to the database!" in the logs? Or anything else that contains "[Consumer]" other than the overloaded message?

The overloaded message that you mentioned occurs when there are rows added by a block change or something like that that should be pushed to the database and the backlog excedes some size. So this looks like somehow the thread that wants to push the rows to the database was unable to do so. But I have no idea how that could happen without any exception or warning.

**Comment by Intelli** [comment]
Regarding the CoreProtect issue, I've been unable to replicate this myself.

Tested on an old CentOS 6.10 install w/ MySQL 5.5.59, and everything works as expected.

**Comment by Brokkonaut** [comment]
Can you try to run the server with the spark plugin and run the command 
`/spark profiler start --thread Logblock-Consumer`
and after some minutes
`/spark profiler stop`
Maybe the thread stack can show where the consumer is hanging.
