### ISSUE TITLE
Archive Table

### ISSUE THREAD

**Issue by DiddiZ** [LogBlock/LogBlock#9]
Feature request: It would be GREAT to have an archive table. So `lb-main` and `lb-main-archive`. The purpose being, I can trim the "main" table to something reasonable (say, 7 or 14 days) and keep insert performance high. But in the event I run a query that is outside of that range, LogBlock could query both the current and archive table. I found query performance with 2 months worth of data was actually reasonable (MySQL rocks), it was just the insert performance with the massive indexes that was lagging.

I know this would complicate the architecture a bit, but maybe it could be done in baby steps. For example, you could just add the archive table & option to use it, and instead of purging data into oblivion, just migrate it to the archive table for now. Then as time goes on, you could actually add it to the query interface to seamlessly use both tables.

**Comment by Brokkonaut** [comment]
As we have bulk inserts in the main table now, I don't think there is a reason for an additional archive table
